// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// AccessLogApplyConfiguration represents a declarative configuration of the AccessLog type for use
// with apply.
//
// AccessLog represents the top-level access log configuration.
type AccessLogApplyConfiguration struct {
	// Output access logs to local file
	FileSink *FileSinkApplyConfiguration `json:"fileSink,omitempty"`
	// Send access logs to gRPC service
	GrpcService *AccessLogGrpcServiceApplyConfiguration `json:"grpcService,omitempty"`
	// Send access logs to an OTel collector
	OpenTelemetry *OpenTelemetryAccessLogServiceApplyConfiguration `json:"openTelemetry,omitempty"`
	// Filter access logs configuration
	Filter *AccessLogFilterApplyConfiguration `json:"filter,omitempty"`
}

// AccessLogApplyConfiguration constructs a declarative configuration of the AccessLog type for use with
// apply.
func AccessLog() *AccessLogApplyConfiguration {
	return &AccessLogApplyConfiguration{}
}

// WithFileSink sets the FileSink field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FileSink field is set to the value of the last call.
func (b *AccessLogApplyConfiguration) WithFileSink(value *FileSinkApplyConfiguration) *AccessLogApplyConfiguration {
	b.FileSink = value
	return b
}

// WithGrpcService sets the GrpcService field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GrpcService field is set to the value of the last call.
func (b *AccessLogApplyConfiguration) WithGrpcService(value *AccessLogGrpcServiceApplyConfiguration) *AccessLogApplyConfiguration {
	b.GrpcService = value
	return b
}

// WithOpenTelemetry sets the OpenTelemetry field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OpenTelemetry field is set to the value of the last call.
func (b *AccessLogApplyConfiguration) WithOpenTelemetry(value *OpenTelemetryAccessLogServiceApplyConfiguration) *AccessLogApplyConfiguration {
	b.OpenTelemetry = value
	return b
}

// WithFilter sets the Filter field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Filter field is set to the value of the last call.
func (b *AccessLogApplyConfiguration) WithFilter(value *AccessLogFilterApplyConfiguration) *AccessLogApplyConfiguration {
	b.Filter = value
	return b
}
