// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// AgentgatewayApplyConfiguration represents a declarative configuration of the Agentgateway type for use
// with apply.
//
// Agentgateway configures the agentgateway dataplane integration to be enabled if the `agentgateway` GatewayClass is used.
type AgentgatewayApplyConfiguration struct {
	// Whether to enable the extension.
	Enabled *bool `json:"enabled,omitempty"`
	// Log level for the agentgateway. Defaults to info.
	// Levels include "trace", "debug", "info", "error", "warn". See: https://docs.rs/tracing/latest/tracing/struct.Level.html
	LogLevel *string `json:"logLevel,omitempty"`
	// The agentgateway container image. See
	// https://kubernetes.io/docs/concepts/containers/images
	// for details.
	//
	// Default values, which may be overridden individually:
	//
	// registry: ghcr.io/agentgateway
	// repository: agentgateway
	// tag: <agentgateway version>
	// pullPolicy: IfNotPresent
	Image *ImageApplyConfiguration `json:"image,omitempty"`
	// The security context for this container. See
	// https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.26/#securitycontext-v1-core
	// for details.
	SecurityContext *v1.SecurityContext `json:"securityContext,omitempty"`
	// The compute resources required by this container. See
	// https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
	// for details.
	Resources *v1.ResourceRequirements `json:"resources,omitempty"`
	// The container environment variables.
	Env []v1.EnvVar `json:"env,omitempty"`
	// Name of the custom configmap to use instead of the default generated one.
	// When set, the agent gateway will use this configmap instead of creating the default one.
	// The configmap must contain a 'config.yaml' key with the agent gateway configuration.
	CustomConfigMapName *string `json:"customConfigMapName,omitempty"`
	// Additional volume mounts to add to the container. See
	// https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.26/#volumemount-v1-core
	// for details.
	ExtraVolumeMounts []v1.VolumeMount `json:"extraVolumeMounts,omitempty"`
}

// AgentgatewayApplyConfiguration constructs a declarative configuration of the Agentgateway type for use with
// apply.
func Agentgateway() *AgentgatewayApplyConfiguration {
	return &AgentgatewayApplyConfiguration{}
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *AgentgatewayApplyConfiguration) WithEnabled(value bool) *AgentgatewayApplyConfiguration {
	b.Enabled = &value
	return b
}

// WithLogLevel sets the LogLevel field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LogLevel field is set to the value of the last call.
func (b *AgentgatewayApplyConfiguration) WithLogLevel(value string) *AgentgatewayApplyConfiguration {
	b.LogLevel = &value
	return b
}

// WithImage sets the Image field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Image field is set to the value of the last call.
func (b *AgentgatewayApplyConfiguration) WithImage(value *ImageApplyConfiguration) *AgentgatewayApplyConfiguration {
	b.Image = value
	return b
}

// WithSecurityContext sets the SecurityContext field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecurityContext field is set to the value of the last call.
func (b *AgentgatewayApplyConfiguration) WithSecurityContext(value v1.SecurityContext) *AgentgatewayApplyConfiguration {
	b.SecurityContext = &value
	return b
}

// WithResources sets the Resources field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Resources field is set to the value of the last call.
func (b *AgentgatewayApplyConfiguration) WithResources(value v1.ResourceRequirements) *AgentgatewayApplyConfiguration {
	b.Resources = &value
	return b
}

// WithEnv adds the given value to the Env field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Env field.
func (b *AgentgatewayApplyConfiguration) WithEnv(values ...v1.EnvVar) *AgentgatewayApplyConfiguration {
	for i := range values {
		b.Env = append(b.Env, values[i])
	}
	return b
}

// WithCustomConfigMapName sets the CustomConfigMapName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CustomConfigMapName field is set to the value of the last call.
func (b *AgentgatewayApplyConfiguration) WithCustomConfigMapName(value string) *AgentgatewayApplyConfiguration {
	b.CustomConfigMapName = &value
	return b
}

// WithExtraVolumeMounts adds the given value to the ExtraVolumeMounts field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ExtraVolumeMounts field.
func (b *AgentgatewayApplyConfiguration) WithExtraVolumeMounts(values ...v1.VolumeMount) *AgentgatewayApplyConfiguration {
	for i := range values {
		b.ExtraVolumeMounts = append(b.ExtraVolumeMounts, values[i])
	}
	return b
}
