// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	v1 "sigs.k8s.io/gateway-api/apis/v1"

	apiv1alpha1 "github.com/kgateway-dev/kgateway/v2/api/v1alpha1"
)

// AiExtensionTraceApplyConfiguration represents a declarative configuration of the AiExtensionTrace type for use
// with apply.
//
// AiExtensionTrace defines the tracing configuration for the AI extension
type AiExtensionTraceApplyConfiguration struct {
	// EndPoint specifies the URL of the OTLP Exporter for traces.
	// Example: "http://my-otel-collector.svc.cluster.local:4317"
	// https://opentelemetry.io/docs/languages/sdk-configuration/otlp-exporter/#otel_exporter_otlp_traces_endpoint
	EndPoint *v1.AbsoluteURI `json:"endpoint,omitempty"`
	// Sampler defines the sampling strategy for OpenTelemetry traces.
	// Sampling helps in reducing the volume of trace data by selectively
	// recording only a subset of traces.
	// https://opentelemetry.io/docs/languages/sdk-configuration/general/#otel_traces_sampler
	Sampler *OTelTracesSamplerApplyConfiguration `json:"sampler,omitempty"`
	// OTLPTimeout specifies timeout configurations for OTLP (OpenTelemetry Protocol) exports.
	// It allows setting general and trace-specific timeouts for sending data.
	// https://opentelemetry.io/docs/languages/sdk-configuration/otlp-exporter/#otel_exporter_otlp_traces_timeout
	Timeout *metav1.Duration `json:"timeout,omitempty"`
	// OTLPProtocol specifies the protocol to be used for OTLP exports.
	// This determines how tracing data is serialized and transported (e.g., gRPC, HTTP/Protobuf).
	// https://opentelemetry.io/docs/languages/sdk-configuration/otlp-exporter/#otel_exporter_otlp_traces_protocol
	Protocol *apiv1alpha1.OTLPTracesProtocolType `json:"protocol,omitempty"`
}

// AiExtensionTraceApplyConfiguration constructs a declarative configuration of the AiExtensionTrace type for use with
// apply.
func AiExtensionTrace() *AiExtensionTraceApplyConfiguration {
	return &AiExtensionTraceApplyConfiguration{}
}

// WithEndPoint sets the EndPoint field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EndPoint field is set to the value of the last call.
func (b *AiExtensionTraceApplyConfiguration) WithEndPoint(value v1.AbsoluteURI) *AiExtensionTraceApplyConfiguration {
	b.EndPoint = &value
	return b
}

// WithSampler sets the Sampler field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Sampler field is set to the value of the last call.
func (b *AiExtensionTraceApplyConfiguration) WithSampler(value *OTelTracesSamplerApplyConfiguration) *AiExtensionTraceApplyConfiguration {
	b.Sampler = value
	return b
}

// WithTimeout sets the Timeout field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Timeout field is set to the value of the last call.
func (b *AiExtensionTraceApplyConfiguration) WithTimeout(value metav1.Duration) *AiExtensionTraceApplyConfiguration {
	b.Timeout = &value
	return b
}

// WithProtocol sets the Protocol field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Protocol field is set to the value of the last call.
func (b *AiExtensionTraceApplyConfiguration) WithProtocol(value apiv1alpha1.OTLPTracesProtocolType) *AiExtensionTraceApplyConfiguration {
	b.Protocol = &value
	return b
}
