// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/kgateway-dev/kgateway/v2/api/v1alpha1"
)

// AIPolicyApplyConfiguration represents a declarative configuration of the AIPolicy type for use
// with apply.
//
// AIPolicy config is used to configure the behavior of the LLM provider
// on the level of individual routes. These route settings, such as prompt enrichment,
// retrieval augmented generation (RAG), and semantic caching, are applicable only
// for routes that send requests to an LLM provider backend.
type AIPolicyApplyConfiguration struct {
	// Enrich requests sent to the LLM provider by appending and prepending system prompts.
	// This can be configured only for LLM providers that use the `CHAT` or `CHAT_STREAMING` API route type.
	PromptEnrichment *AIPromptEnrichmentApplyConfiguration `json:"promptEnrichment,omitempty"`
	// Set up prompt guards to block unwanted requests to the LLM provider and mask sensitive data.
	// Prompt guards can be used to reject requests based on the content of the prompt, as well as
	// mask responses based on the content of the response.
	PromptGuard *AIPromptGuardApplyConfiguration `json:"promptGuard,omitempty"`
	// Provide defaults to merge with user input fields.
	// Defaults do _not_ override the user input fields, unless you explicitly set `override` to `true`.
	Defaults []FieldDefaultApplyConfiguration `json:"defaults,omitempty"`
	// The type of route to the LLM provider API. Currently, `CHAT` and `CHAT_STREAMING` are supported.
	// Note: This field is not applicable when using agentgateway
	RouteType *apiv1alpha1.RouteType `json:"routeType,omitempty"`
}

// AIPolicyApplyConfiguration constructs a declarative configuration of the AIPolicy type for use with
// apply.
func AIPolicy() *AIPolicyApplyConfiguration {
	return &AIPolicyApplyConfiguration{}
}

// WithPromptEnrichment sets the PromptEnrichment field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PromptEnrichment field is set to the value of the last call.
func (b *AIPolicyApplyConfiguration) WithPromptEnrichment(value *AIPromptEnrichmentApplyConfiguration) *AIPolicyApplyConfiguration {
	b.PromptEnrichment = value
	return b
}

// WithPromptGuard sets the PromptGuard field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PromptGuard field is set to the value of the last call.
func (b *AIPolicyApplyConfiguration) WithPromptGuard(value *AIPromptGuardApplyConfiguration) *AIPolicyApplyConfiguration {
	b.PromptGuard = value
	return b
}

// WithDefaults adds the given value to the Defaults field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Defaults field.
func (b *AIPolicyApplyConfiguration) WithDefaults(values ...*FieldDefaultApplyConfiguration) *AIPolicyApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithDefaults")
		}
		b.Defaults = append(b.Defaults, *values[i])
	}
	return b
}

// WithRouteType sets the RouteType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RouteType field is set to the value of the last call.
func (b *AIPolicyApplyConfiguration) WithRouteType(value apiv1alpha1.RouteType) *AIPolicyApplyConfiguration {
	b.RouteType = &value
	return b
}
