// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// AIPromptGuardApplyConfiguration represents a declarative configuration of the AIPromptGuard type for use
// with apply.
//
// AIPromptGuard configures a prompt guards to block unwanted requests to the LLM provider and mask sensitive data.
// Prompt guards can be used to reject requests based on the content of the prompt, as well as
// mask responses based on the content of the response.
//
// This example rejects any request prompts that contain
// the string "credit card", and masks any credit card numbers in the response.
// ```yaml
// promptGuard:
//
// request:
// customResponse:
// message: "Rejected due to inappropriate content"
// regex:
// action: REJECT
// matches:
// - pattern: "credit card"
// name: "CC"
// response:
// regex:
// builtins:
// - CREDIT_CARD
// action: MASK
//
// ```
type AIPromptGuardApplyConfiguration struct {
	// Prompt guards to apply to requests sent by the client.
	Request *PromptguardRequestApplyConfiguration `json:"request,omitempty"`
	// Prompt guards to apply to responses returned by the LLM provider.
	Response *PromptguardResponseApplyConfiguration `json:"response,omitempty"`
}

// AIPromptGuardApplyConfiguration constructs a declarative configuration of the AIPromptGuard type for use with
// apply.
func AIPromptGuard() *AIPromptGuardApplyConfiguration {
	return &AIPromptGuardApplyConfiguration{}
}

// WithRequest sets the Request field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Request field is set to the value of the last call.
func (b *AIPromptGuardApplyConfiguration) WithRequest(value *PromptguardRequestApplyConfiguration) *AIPromptGuardApplyConfiguration {
	b.Request = value
	return b
}

// WithResponse sets the Response field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Response field is set to the value of the last call.
func (b *AIPromptGuardApplyConfiguration) WithResponse(value *PromptguardResponseApplyConfiguration) *AIPromptGuardApplyConfiguration {
	b.Response = value
	return b
}
