// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// AwsBackendApplyConfiguration represents a declarative configuration of the AwsBackend type for use
// with apply.
//
// AwsBackend is the AWS backend configuration.
type AwsBackendApplyConfiguration struct {
	// Lambda configures the AWS lambda service.
	Lambda *AwsLambdaApplyConfiguration `json:"lambda,omitempty"`
	// AccountId is the AWS account ID to use for the backend.
	AccountId *string `json:"accountId,omitempty"`
	// Auth specifies an explicit AWS authentication method for the backend.
	// When omitted, the following credential providers are tried in order, stopping when one
	// of them returns an access key ID and a secret access key (the session token is optional):
	// 1. Environment variables: when the environment variables AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, and AWS_SESSION_TOKEN are set.
	// 2. AssumeRoleWithWebIdentity API call: when the environment variables AWS_WEB_IDENTITY_TOKEN_FILE and AWS_ROLE_ARN are set.
	// 3. EKS Pod Identity: when the environment variable AWS_CONTAINER_AUTHORIZATION_TOKEN_FILE is set.
	//
	// See the Envoy docs for more info:
	// https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/aws_request_signing_filter#credentials
	Auth *AwsAuthApplyConfiguration `json:"auth,omitempty"`
	// Region is the AWS region to use for the backend.
	// Defaults to us-east-1 if not specified.
	Region *string `json:"region,omitempty"`
}

// AwsBackendApplyConfiguration constructs a declarative configuration of the AwsBackend type for use with
// apply.
func AwsBackend() *AwsBackendApplyConfiguration {
	return &AwsBackendApplyConfiguration{}
}

// WithLambda sets the Lambda field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Lambda field is set to the value of the last call.
func (b *AwsBackendApplyConfiguration) WithLambda(value *AwsLambdaApplyConfiguration) *AwsBackendApplyConfiguration {
	b.Lambda = value
	return b
}

// WithAccountId sets the AccountId field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AccountId field is set to the value of the last call.
func (b *AwsBackendApplyConfiguration) WithAccountId(value string) *AwsBackendApplyConfiguration {
	b.AccountId = &value
	return b
}

// WithAuth sets the Auth field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Auth field is set to the value of the last call.
func (b *AwsBackendApplyConfiguration) WithAuth(value *AwsAuthApplyConfiguration) *AwsBackendApplyConfiguration {
	b.Auth = value
	return b
}

// WithRegion sets the Region field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Region field is set to the value of the last call.
func (b *AwsBackendApplyConfiguration) WithRegion(value string) *AwsBackendApplyConfiguration {
	b.Region = &value
	return b
}
