// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/kgateway-dev/kgateway/v2/api/v1alpha1"
)

// AwsLambdaApplyConfiguration represents a declarative configuration of the AwsLambda type for use
// with apply.
//
// AwsLambda configures the AWS lambda service.
type AwsLambdaApplyConfiguration struct {
	// EndpointURL is the URL or domain for the Lambda service. This is primarily
	// useful for testing and development purposes. When omitted, the default
	// lambda hostname will be used.
	EndpointURL *string `json:"endpointURL,omitempty"`
	// FunctionName is the name of the Lambda function to invoke.
	FunctionName *string `json:"functionName,omitempty"`
	// InvocationMode defines how to invoke the Lambda function.
	// Defaults to Sync.
	InvocationMode *string `json:"invocationMode,omitempty"`
	// Qualifier is the alias or version for the Lambda function.
	// Valid values include a numeric version (e.g. "1"), an alias name
	// (alphanumeric plus "-" or "_"), or the special literal "$LATEST".
	Qualifier *string `json:"qualifier,omitempty"`
	// PayloadTransformation specifies payload transformation mode before it is sent to the Lambda function.
	// Defaults to Envoy.
	PayloadTransformMode *apiv1alpha1.AWSLambdaPayloadTransformMode `json:"payloadTransformMode,omitempty"`
}

// AwsLambdaApplyConfiguration constructs a declarative configuration of the AwsLambda type for use with
// apply.
func AwsLambda() *AwsLambdaApplyConfiguration {
	return &AwsLambdaApplyConfiguration{}
}

// WithEndpointURL sets the EndpointURL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EndpointURL field is set to the value of the last call.
func (b *AwsLambdaApplyConfiguration) WithEndpointURL(value string) *AwsLambdaApplyConfiguration {
	b.EndpointURL = &value
	return b
}

// WithFunctionName sets the FunctionName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FunctionName field is set to the value of the last call.
func (b *AwsLambdaApplyConfiguration) WithFunctionName(value string) *AwsLambdaApplyConfiguration {
	b.FunctionName = &value
	return b
}

// WithInvocationMode sets the InvocationMode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InvocationMode field is set to the value of the last call.
func (b *AwsLambdaApplyConfiguration) WithInvocationMode(value string) *AwsLambdaApplyConfiguration {
	b.InvocationMode = &value
	return b
}

// WithQualifier sets the Qualifier field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Qualifier field is set to the value of the last call.
func (b *AwsLambdaApplyConfiguration) WithQualifier(value string) *AwsLambdaApplyConfiguration {
	b.Qualifier = &value
	return b
}

// WithPayloadTransformMode sets the PayloadTransformMode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PayloadTransformMode field is set to the value of the last call.
func (b *AwsLambdaApplyConfiguration) WithPayloadTransformMode(value apiv1alpha1.AWSLambdaPayloadTransformMode) *AwsLambdaApplyConfiguration {
	b.PayloadTransformMode = &value
	return b
}
