// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// AzureOpenAIConfigApplyConfiguration represents a declarative configuration of the AzureOpenAIConfig type for use
// with apply.
//
// AzureOpenAIConfig settings for the [Azure OpenAI](https://learn.microsoft.com/en-us/azure/ai-services/openai/) LLM provider.
type AzureOpenAIConfigApplyConfiguration struct {
	// The authorization token that the AI gateway uses to access the Azure OpenAI API.
	// This token is automatically sent in the `api-key` header of the request.
	AuthToken *SingleAuthTokenApplyConfiguration `json:"authToken,omitempty"`
	// The endpoint for the Azure OpenAI API to use, such as `my-endpoint.openai.azure.com`.
	// If the scheme is included, it is stripped.
	Endpoint *string `json:"endpoint,omitempty"`
	// The name of the Azure OpenAI model deployment to use.
	// For more information, see the [Azure OpenAI model docs](https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/models).
	DeploymentName *string `json:"deploymentName,omitempty"`
	// The version of the Azure OpenAI API to use.
	// For more information, see the [Azure OpenAI API version reference](https://learn.microsoft.com/en-us/azure/ai-services/openai/reference#api-specs).
	ApiVersion *string `json:"apiVersion,omitempty"`
}

// AzureOpenAIConfigApplyConfiguration constructs a declarative configuration of the AzureOpenAIConfig type for use with
// apply.
func AzureOpenAIConfig() *AzureOpenAIConfigApplyConfiguration {
	return &AzureOpenAIConfigApplyConfiguration{}
}

// WithAuthToken sets the AuthToken field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AuthToken field is set to the value of the last call.
func (b *AzureOpenAIConfigApplyConfiguration) WithAuthToken(value *SingleAuthTokenApplyConfiguration) *AzureOpenAIConfigApplyConfiguration {
	b.AuthToken = value
	return b
}

// WithEndpoint sets the Endpoint field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Endpoint field is set to the value of the last call.
func (b *AzureOpenAIConfigApplyConfiguration) WithEndpoint(value string) *AzureOpenAIConfigApplyConfiguration {
	b.Endpoint = &value
	return b
}

// WithDeploymentName sets the DeploymentName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeploymentName field is set to the value of the last call.
func (b *AzureOpenAIConfigApplyConfiguration) WithDeploymentName(value string) *AzureOpenAIConfigApplyConfiguration {
	b.DeploymentName = &value
	return b
}

// WithApiVersion sets the ApiVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ApiVersion field is set to the value of the last call.
func (b *AzureOpenAIConfigApplyConfiguration) WithApiVersion(value string) *AzureOpenAIConfigApplyConfiguration {
	b.ApiVersion = &value
	return b
}
