// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// BackendConfigPolicySpecApplyConfiguration represents a declarative configuration of the BackendConfigPolicySpec type for use
// with apply.
//
// BackendConfigPolicySpec defines the desired state of BackendConfigPolicy.
type BackendConfigPolicySpecApplyConfiguration struct {
	// TargetRefs specifies the target references to attach the policy to.
	TargetRefs []LocalPolicyTargetReferenceApplyConfiguration `json:"targetRefs,omitempty"`
	// TargetSelectors specifies the target selectors to select resources to attach the policy to.
	TargetSelectors []LocalPolicyTargetSelectorApplyConfiguration `json:"targetSelectors,omitempty"`
	// The timeout for new network connections to hosts in the cluster.
	ConnectTimeout *v1.Duration `json:"connectTimeout,omitempty"`
	// Soft limit on the size of the cluster's connections read and write buffers.
	// If unspecified, an implementation-defined default is applied (1MiB).
	PerConnectionBufferLimitBytes *int32 `json:"perConnectionBufferLimitBytes,omitempty"`
	// Configure OS-level TCP keepalive checks.
	TCPKeepalive *TCPKeepaliveApplyConfiguration `json:"tcpKeepalive,omitempty"`
	// Additional options when handling HTTP requests upstream, applicable to
	// both HTTP1 and HTTP2 requests.
	CommonHttpProtocolOptions *CommonHttpProtocolOptionsApplyConfiguration `json:"commonHttpProtocolOptions,omitempty"`
	// Additional options when handling HTTP1 requests upstream.
	Http1ProtocolOptions *Http1ProtocolOptionsApplyConfiguration `json:"http1ProtocolOptions,omitempty"`
	// Http2ProtocolOptions contains the options necessary to configure HTTP/2 backends.
	// Note: Http2ProtocolOptions can only be applied to HTTP/2 backends.
	// See [Envoy documentation](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/transport_sockets/tls/v3/tls.proto#envoy-v3-api-msg-extensions-transport-sockets-tls-v3-sslconfig) for more details.
	Http2ProtocolOptions *Http2ProtocolOptionsApplyConfiguration `json:"http2ProtocolOptions,omitempty"`
	// TLS contains the options necessary to configure a backend to use TLS origination.
	// See [Envoy documentation](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/transport_sockets/tls/v3/tls.proto#envoy-v3-api-msg-extensions-transport-sockets-tls-v3-sslconfig) for more details.
	TLS *TLSApplyConfiguration `json:"tls,omitempty"`
	// LoadBalancer contains the options necessary to configure the load balancer.
	LoadBalancer *LoadBalancerApplyConfiguration `json:"loadBalancer,omitempty"`
	// HealthCheck contains the options necessary to configure the health check.
	HealthCheck *HealthCheckApplyConfiguration `json:"healthCheck,omitempty"`
	// OutlierDetection contains the options necessary to configure passive health checking.
	OutlierDetection *OutlierDetectionApplyConfiguration `json:"outlierDetection,omitempty"`
}

// BackendConfigPolicySpecApplyConfiguration constructs a declarative configuration of the BackendConfigPolicySpec type for use with
// apply.
func BackendConfigPolicySpec() *BackendConfigPolicySpecApplyConfiguration {
	return &BackendConfigPolicySpecApplyConfiguration{}
}

// WithTargetRefs adds the given value to the TargetRefs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the TargetRefs field.
func (b *BackendConfigPolicySpecApplyConfiguration) WithTargetRefs(values ...*LocalPolicyTargetReferenceApplyConfiguration) *BackendConfigPolicySpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithTargetRefs")
		}
		b.TargetRefs = append(b.TargetRefs, *values[i])
	}
	return b
}

// WithTargetSelectors adds the given value to the TargetSelectors field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the TargetSelectors field.
func (b *BackendConfigPolicySpecApplyConfiguration) WithTargetSelectors(values ...*LocalPolicyTargetSelectorApplyConfiguration) *BackendConfigPolicySpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithTargetSelectors")
		}
		b.TargetSelectors = append(b.TargetSelectors, *values[i])
	}
	return b
}

// WithConnectTimeout sets the ConnectTimeout field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConnectTimeout field is set to the value of the last call.
func (b *BackendConfigPolicySpecApplyConfiguration) WithConnectTimeout(value v1.Duration) *BackendConfigPolicySpecApplyConfiguration {
	b.ConnectTimeout = &value
	return b
}

// WithPerConnectionBufferLimitBytes sets the PerConnectionBufferLimitBytes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PerConnectionBufferLimitBytes field is set to the value of the last call.
func (b *BackendConfigPolicySpecApplyConfiguration) WithPerConnectionBufferLimitBytes(value int32) *BackendConfigPolicySpecApplyConfiguration {
	b.PerConnectionBufferLimitBytes = &value
	return b
}

// WithTCPKeepalive sets the TCPKeepalive field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TCPKeepalive field is set to the value of the last call.
func (b *BackendConfigPolicySpecApplyConfiguration) WithTCPKeepalive(value *TCPKeepaliveApplyConfiguration) *BackendConfigPolicySpecApplyConfiguration {
	b.TCPKeepalive = value
	return b
}

// WithCommonHttpProtocolOptions sets the CommonHttpProtocolOptions field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CommonHttpProtocolOptions field is set to the value of the last call.
func (b *BackendConfigPolicySpecApplyConfiguration) WithCommonHttpProtocolOptions(value *CommonHttpProtocolOptionsApplyConfiguration) *BackendConfigPolicySpecApplyConfiguration {
	b.CommonHttpProtocolOptions = value
	return b
}

// WithHttp1ProtocolOptions sets the Http1ProtocolOptions field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Http1ProtocolOptions field is set to the value of the last call.
func (b *BackendConfigPolicySpecApplyConfiguration) WithHttp1ProtocolOptions(value *Http1ProtocolOptionsApplyConfiguration) *BackendConfigPolicySpecApplyConfiguration {
	b.Http1ProtocolOptions = value
	return b
}

// WithHttp2ProtocolOptions sets the Http2ProtocolOptions field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Http2ProtocolOptions field is set to the value of the last call.
func (b *BackendConfigPolicySpecApplyConfiguration) WithHttp2ProtocolOptions(value *Http2ProtocolOptionsApplyConfiguration) *BackendConfigPolicySpecApplyConfiguration {
	b.Http2ProtocolOptions = value
	return b
}

// WithTLS sets the TLS field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TLS field is set to the value of the last call.
func (b *BackendConfigPolicySpecApplyConfiguration) WithTLS(value *TLSApplyConfiguration) *BackendConfigPolicySpecApplyConfiguration {
	b.TLS = value
	return b
}

// WithLoadBalancer sets the LoadBalancer field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LoadBalancer field is set to the value of the last call.
func (b *BackendConfigPolicySpecApplyConfiguration) WithLoadBalancer(value *LoadBalancerApplyConfiguration) *BackendConfigPolicySpecApplyConfiguration {
	b.LoadBalancer = value
	return b
}

// WithHealthCheck sets the HealthCheck field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HealthCheck field is set to the value of the last call.
func (b *BackendConfigPolicySpecApplyConfiguration) WithHealthCheck(value *HealthCheckApplyConfiguration) *BackendConfigPolicySpecApplyConfiguration {
	b.HealthCheck = value
	return b
}

// WithOutlierDetection sets the OutlierDetection field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OutlierDetection field is set to the value of the last call.
func (b *BackendConfigPolicySpecApplyConfiguration) WithOutlierDetection(value *OutlierDetectionApplyConfiguration) *BackendConfigPolicySpecApplyConfiguration {
	b.OutlierDetection = value
	return b
}
