// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// BackoffStrategyApplyConfiguration represents a declarative configuration of the BackoffStrategy type for use
// with apply.
//
// Configuration defining a jittered exponential back off strategy.
// Ref: https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/backoff.proto#envoy-v3-api-msg-config-core-v3-backoffstrategy
type BackoffStrategyApplyConfiguration struct {
	// The base interval to be used for the next back off computation. It should be greater than zero and less than or equal to max_interval.
	BaseInterval *v1.Duration `json:"baseInterval,omitempty"`
	// Specifies the maximum interval between retries. This parameter is optional, but must be greater than or equal to the base_interval if set. The default is 10 times the base_interval.
	MaxInterval *v1.Duration `json:"maxInterval,omitempty"`
}

// BackoffStrategyApplyConfiguration constructs a declarative configuration of the BackoffStrategy type for use with
// apply.
func BackoffStrategy() *BackoffStrategyApplyConfiguration {
	return &BackoffStrategyApplyConfiguration{}
}

// WithBaseInterval sets the BaseInterval field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BaseInterval field is set to the value of the last call.
func (b *BackoffStrategyApplyConfiguration) WithBaseInterval(value v1.Duration) *BackoffStrategyApplyConfiguration {
	b.BaseInterval = &value
	return b
}

// WithMaxInterval sets the MaxInterval field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxInterval field is set to the value of the last call.
func (b *BackoffStrategyApplyConfiguration) WithMaxInterval(value v1.Duration) *BackoffStrategyApplyConfiguration {
	b.MaxInterval = &value
	return b
}
