// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// BedrockConfigApplyConfiguration represents a declarative configuration of the BedrockConfig type for use
// with apply.
type BedrockConfigApplyConfiguration struct {
	// Auth specifies an explicit AWS authentication method for the backend.
	// When omitted, the following credential providers are tried in order, stopping when one
	// of them returns an access key ID and a secret access key (the session token is optional):
	// 1. Environment variables: when the environment variables AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, and AWS_SESSION_TOKEN are set.
	// 2. AssumeRoleWithWebIdentity API call: when the environment variables AWS_WEB_IDENTITY_TOKEN_FILE and AWS_ROLE_ARN are set.
	// 3. EKS Pod Identity: when the environment variable AWS_CONTAINER_AUTHORIZATION_TOKEN_FILE is set.
	//
	// See the Envoy docs for more info:
	// https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/aws_request_signing_filter#credentials
	Auth *AwsAuthApplyConfiguration `json:"auth,omitempty"`
	// Optional: Override the model ID.
	// If unset, the model is taken from the request.
	// See <https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html>
	Model *string `json:"model,omitempty"`
	// Region is the AWS region to use for the backend.
	// Defaults to us-east-1 if not specified.
	Region *string `json:"region,omitempty"`
	// Guardrail configures the Guardrail policy to use for the backend. See <https://docs.aws.amazon.com/bedrock/latest/userguide/guardrails.html>
	// If not specified, the AWS Guardrail policy will not be used.
	Guardrail *AWSGuardrailConfigApplyConfiguration `json:"guardrail,omitempty"`
}

// BedrockConfigApplyConfiguration constructs a declarative configuration of the BedrockConfig type for use with
// apply.
func BedrockConfig() *BedrockConfigApplyConfiguration {
	return &BedrockConfigApplyConfiguration{}
}

// WithAuth sets the Auth field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Auth field is set to the value of the last call.
func (b *BedrockConfigApplyConfiguration) WithAuth(value *AwsAuthApplyConfiguration) *BedrockConfigApplyConfiguration {
	b.Auth = value
	return b
}

// WithModel sets the Model field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Model field is set to the value of the last call.
func (b *BedrockConfigApplyConfiguration) WithModel(value string) *BedrockConfigApplyConfiguration {
	b.Model = &value
	return b
}

// WithRegion sets the Region field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Region field is set to the value of the last call.
func (b *BedrockConfigApplyConfiguration) WithRegion(value string) *BedrockConfigApplyConfiguration {
	b.Region = &value
	return b
}

// WithGuardrail sets the Guardrail field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Guardrail field is set to the value of the last call.
func (b *BedrockConfigApplyConfiguration) WithGuardrail(value *AWSGuardrailConfigApplyConfiguration) *BedrockConfigApplyConfiguration {
	b.Guardrail = value
	return b
}
