// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/kgateway-dev/kgateway/v2/api/v1alpha1"
)

// BodyTransformationApplyConfiguration represents a declarative configuration of the BodyTransformation type for use
// with apply.
//
// BodyTransformation controls how the body should be parsed and transformed.
type BodyTransformationApplyConfiguration struct {
	// ParseAs defines what auto formatting should be applied to the body.
	// This can make interacting with keys within a json body much easier if AsJson is selected.
	// This field is only supported for kgateway (Envoy) data plane and is ignored by agentgateway.
	// For agentgateway, use json(request.body) or json(response.body) directly in CEL expressions.
	ParseAs *apiv1alpha1.BodyParseBehavior `json:"parseAs,omitempty"`
	// Value is the template to apply to generate the output value for the body.
	// Inja templates are supported for Envoy-based data planes only.
	// CEL expressions are supported for agentgateway data plane only.
	// The system will auto-detect the appropriate template format based on the data plane.
	Value *apiv1alpha1.Template `json:"value,omitempty"`
}

// BodyTransformationApplyConfiguration constructs a declarative configuration of the BodyTransformation type for use with
// apply.
func BodyTransformation() *BodyTransformationApplyConfiguration {
	return &BodyTransformationApplyConfiguration{}
}

// WithParseAs sets the ParseAs field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ParseAs field is set to the value of the last call.
func (b *BodyTransformationApplyConfiguration) WithParseAs(value apiv1alpha1.BodyParseBehavior) *BodyTransformationApplyConfiguration {
	b.ParseAs = &value
	return b
}

// WithValue sets the Value field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Value field is set to the value of the last call.
func (b *BodyTransformationApplyConfiguration) WithValue(value apiv1alpha1.Template) *BodyTransformationApplyConfiguration {
	b.Value = &value
	return b
}
