// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	v1 "sigs.k8s.io/gateway-api/apis/v1"
)

// CommonGrpcServiceApplyConfiguration represents a declarative configuration of the CommonGrpcService type for use
// with apply.
//
// Common gRPC service configuration created by setting `envoy_grpc“ as the gRPC client
// Ref: https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/grpc_service.proto#envoy-v3-api-msg-config-core-v3-grpcservice
// Ref: https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/grpc_service.proto#envoy-v3-api-msg-config-core-v3-grpcservice-envoygrpc
type CommonGrpcServiceApplyConfiguration struct {
	// The backend gRPC service. Can be any type of supported backend (Kubernetes Service, kgateway Backend, etc..)
	BackendRef *v1.BackendRef `json:"backendRef,omitempty"`
	// The :authority header in the grpc request. If this field is not set, the authority header value will be cluster_name.
	// Note that this authority does not override the SNI. The SNI is provided by the transport socket of the cluster.
	Authority *string `json:"authority,omitempty"`
	// Maximum gRPC message size that is allowed to be received. If a message over this limit is received, the gRPC stream is terminated with the RESOURCE_EXHAUSTED error.
	// Defaults to 0, which means unlimited.
	MaxReceiveMessageLength *int32 `json:"maxReceiveMessageLength,omitempty"`
	// This provides gRPC client level control over envoy generated headers. If false, the header will be sent but it can be overridden by per stream option. If true, the header will be removed and can not be overridden by per stream option. Default to false.
	SkipEnvoyHeaders *bool `json:"skipEnvoyHeaders,omitempty"`
	// The timeout for the gRPC request. This is the timeout for a specific request
	Timeout *metav1.Duration `json:"timeout,omitempty"`
	// Additional metadata to include in streams initiated to the GrpcService.
	// This can be used for scenarios in which additional ad hoc authorization headers (e.g. x-foo-bar: baz-key) are to be injected
	InitialMetadata []HeaderValueApplyConfiguration `json:"initialMetadata,omitempty"`
	// Indicates the retry policy for re-establishing the gRPC stream.
	// If max interval is not provided, it will be set to ten times the provided base interval
	RetryPolicy *RetryPolicyApplyConfiguration `json:"retryPolicy,omitempty"`
}

// CommonGrpcServiceApplyConfiguration constructs a declarative configuration of the CommonGrpcService type for use with
// apply.
func CommonGrpcService() *CommonGrpcServiceApplyConfiguration {
	return &CommonGrpcServiceApplyConfiguration{}
}

// WithBackendRef sets the BackendRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BackendRef field is set to the value of the last call.
func (b *CommonGrpcServiceApplyConfiguration) WithBackendRef(value v1.BackendRef) *CommonGrpcServiceApplyConfiguration {
	b.BackendRef = &value
	return b
}

// WithAuthority sets the Authority field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Authority field is set to the value of the last call.
func (b *CommonGrpcServiceApplyConfiguration) WithAuthority(value string) *CommonGrpcServiceApplyConfiguration {
	b.Authority = &value
	return b
}

// WithMaxReceiveMessageLength sets the MaxReceiveMessageLength field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxReceiveMessageLength field is set to the value of the last call.
func (b *CommonGrpcServiceApplyConfiguration) WithMaxReceiveMessageLength(value int32) *CommonGrpcServiceApplyConfiguration {
	b.MaxReceiveMessageLength = &value
	return b
}

// WithSkipEnvoyHeaders sets the SkipEnvoyHeaders field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SkipEnvoyHeaders field is set to the value of the last call.
func (b *CommonGrpcServiceApplyConfiguration) WithSkipEnvoyHeaders(value bool) *CommonGrpcServiceApplyConfiguration {
	b.SkipEnvoyHeaders = &value
	return b
}

// WithTimeout sets the Timeout field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Timeout field is set to the value of the last call.
func (b *CommonGrpcServiceApplyConfiguration) WithTimeout(value metav1.Duration) *CommonGrpcServiceApplyConfiguration {
	b.Timeout = &value
	return b
}

// WithInitialMetadata adds the given value to the InitialMetadata field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the InitialMetadata field.
func (b *CommonGrpcServiceApplyConfiguration) WithInitialMetadata(values ...*HeaderValueApplyConfiguration) *CommonGrpcServiceApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithInitialMetadata")
		}
		b.InitialMetadata = append(b.InitialMetadata, *values[i])
	}
	return b
}

// WithRetryPolicy sets the RetryPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RetryPolicy field is set to the value of the last call.
func (b *CommonGrpcServiceApplyConfiguration) WithRetryPolicy(value *RetryPolicyApplyConfiguration) *CommonGrpcServiceApplyConfiguration {
	b.RetryPolicy = value
	return b
}
