// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// CSRFPolicyApplyConfiguration represents a declarative configuration of the CSRFPolicy type for use
// with apply.
//
// CSRFPolicy can be used to set percent of requests for which the CSRF filter is enabled,
// enable shadow-only mode where policies will be evaluated and tracked, but not enforced and
// add additional source origins that will be allowed in addition to the destination origin.
type CSRFPolicyApplyConfiguration struct {
	// Specifies the percentage of requests for which the CSRF filter is enabled.
	PercentageEnabled *int32 `json:"percentageEnabled,omitempty"`
	// Specifies that CSRF policies will be evaluated and tracked, but not enforced.
	PercentageShadowed *int32 `json:"percentageShadowed,omitempty"`
	// Specifies additional source origins that will be allowed in addition to the destination origin.
	AdditionalOrigins []StringMatcherApplyConfiguration `json:"additionalOrigins,omitempty"`
}

// CSRFPolicyApplyConfiguration constructs a declarative configuration of the CSRFPolicy type for use with
// apply.
func CSRFPolicy() *CSRFPolicyApplyConfiguration {
	return &CSRFPolicyApplyConfiguration{}
}

// WithPercentageEnabled sets the PercentageEnabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PercentageEnabled field is set to the value of the last call.
func (b *CSRFPolicyApplyConfiguration) WithPercentageEnabled(value int32) *CSRFPolicyApplyConfiguration {
	b.PercentageEnabled = &value
	return b
}

// WithPercentageShadowed sets the PercentageShadowed field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PercentageShadowed field is set to the value of the last call.
func (b *CSRFPolicyApplyConfiguration) WithPercentageShadowed(value int32) *CSRFPolicyApplyConfiguration {
	b.PercentageShadowed = &value
	return b
}

// WithAdditionalOrigins adds the given value to the AdditionalOrigins field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AdditionalOrigins field.
func (b *CSRFPolicyApplyConfiguration) WithAdditionalOrigins(values ...*StringMatcherApplyConfiguration) *CSRFPolicyApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithAdditionalOrigins")
		}
		b.AdditionalOrigins = append(b.AdditionalOrigins, *values[i])
	}
	return b
}
