// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/kgateway-dev/kgateway/v2/api/v1alpha1"
)

// CustomAttributeMetadataApplyConfiguration represents a declarative configuration of the CustomAttributeMetadata type for use
// with apply.
//
// Metadata type attribute using MetadataKey to retrieve the protobuf value from Metadata, and populate the attribute value with the canonical JSON representation of it.
// Ref: https://www.envoyproxy.io/docs/envoy/latest/api-v3/type/tracing/v3/custom_tag.proto#type-tracing-v3-customtag-metadata
type CustomAttributeMetadataApplyConfiguration struct {
	// Specify what kind of metadata to obtain attribute value from
	Kind *apiv1alpha1.MetadataKind `json:"kind,omitempty"`
	// Metadata key to define the path to retrieve the attribute value.
	MetadataKey *MetadataKeyApplyConfiguration `json:"metadataKey,omitempty"`
	// When no valid metadata is found, the attribute value would be populated with this default value if specified, otherwise no attribute would be populated.
	DefaultValue *string `json:"defaultValue,omitempty"`
}

// CustomAttributeMetadataApplyConfiguration constructs a declarative configuration of the CustomAttributeMetadata type for use with
// apply.
func CustomAttributeMetadata() *CustomAttributeMetadataApplyConfiguration {
	return &CustomAttributeMetadataApplyConfiguration{}
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *CustomAttributeMetadataApplyConfiguration) WithKind(value apiv1alpha1.MetadataKind) *CustomAttributeMetadataApplyConfiguration {
	b.Kind = &value
	return b
}

// WithMetadataKey sets the MetadataKey field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MetadataKey field is set to the value of the last call.
func (b *CustomAttributeMetadataApplyConfiguration) WithMetadataKey(value *MetadataKeyApplyConfiguration) *CustomAttributeMetadataApplyConfiguration {
	b.MetadataKey = value
	return b
}

// WithDefaultValue sets the DefaultValue field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DefaultValue field is set to the value of the last call.
func (b *CustomAttributeMetadataApplyConfiguration) WithDefaultValue(value string) *CustomAttributeMetadataApplyConfiguration {
	b.DefaultValue = &value
	return b
}
