// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// CustomAttributeLiteralApplyConfiguration represents a declarative configuration of the CustomAttributeLiteral type for use
// with apply.
//
// Literal type attribute with a static value.
// Ref: https://www.envoyproxy.io/docs/envoy/latest/api-v3/type/tracing/v3/custom_tag.proto#type-tracing-v3-customtag-literal
type CustomAttributeLiteralApplyConfiguration struct {
	// Static literal value to populate the attribute value.
	Value *string `json:"value,omitempty"`
}

// CustomAttributeLiteralApplyConfiguration constructs a declarative configuration of the CustomAttributeLiteral type for use with
// apply.
func CustomAttributeLiteral() *CustomAttributeLiteralApplyConfiguration {
	return &CustomAttributeLiteralApplyConfiguration{}
}

// WithValue sets the Value field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Value field is set to the value of the last call.
func (b *CustomAttributeLiteralApplyConfiguration) WithValue(value string) *CustomAttributeLiteralApplyConfiguration {
	b.Value = &value
	return b
}
