// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// CustomAttributeHeaderApplyConfiguration represents a declarative configuration of the CustomAttributeHeader type for use
// with apply.
//
// Header type attribute with header name and default value.
// https://www.envoyproxy.io/docs/envoy/latest/api-v3/type/tracing/v3/custom_tag.proto#type-tracing-v3-customtag-header
type CustomAttributeHeaderApplyConfiguration struct {
	// Header name to obtain the value to populate the attribute value.
	Name *string `json:"name,omitempty"`
	// When the header does not exist, the attribute value will be populated with this default value if specified,
	// otherwise no attribute will be populated.
	DefaultValue *string `json:"defaultValue,omitempty"`
}

// CustomAttributeHeaderApplyConfiguration constructs a declarative configuration of the CustomAttributeHeader type for use with
// apply.
func CustomAttributeHeader() *CustomAttributeHeaderApplyConfiguration {
	return &CustomAttributeHeaderApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *CustomAttributeHeaderApplyConfiguration) WithName(value string) *CustomAttributeHeaderApplyConfiguration {
	b.Name = &value
	return b
}

// WithDefaultValue sets the DefaultValue field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DefaultValue field is set to the value of the last call.
func (b *CustomAttributeHeaderApplyConfiguration) WithDefaultValue(value string) *CustomAttributeHeaderApplyConfiguration {
	b.DefaultValue = &value
	return b
}
