// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// CustomAttributeEnvironmentApplyConfiguration represents a declarative configuration of the CustomAttributeEnvironment type for use
// with apply.
//
// Environment type attribute with environment name and default value.
// Ref: https://www.envoyproxy.io/docs/envoy/latest/api-v3/type/tracing/v3/custom_tag.proto#type-tracing-v3-customtag-environment
type CustomAttributeEnvironmentApplyConfiguration struct {
	// Environment variable name to obtain the value to populate the attribute value.
	Name *string `json:"name,omitempty"`
	// When the environment variable is not found, the attribute value will be populated with this default value if specified,
	// otherwise no attribute will be populated.
	DefaultValue *string `json:"defaultValue,omitempty"`
}

// CustomAttributeEnvironmentApplyConfiguration constructs a declarative configuration of the CustomAttributeEnvironment type for use with
// apply.
func CustomAttributeEnvironment() *CustomAttributeEnvironmentApplyConfiguration {
	return &CustomAttributeEnvironmentApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *CustomAttributeEnvironmentApplyConfiguration) WithName(value string) *CustomAttributeEnvironmentApplyConfiguration {
	b.Name = &value
	return b
}

// WithDefaultValue sets the DefaultValue field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DefaultValue field is set to the value of the last call.
func (b *CustomAttributeEnvironmentApplyConfiguration) WithDefaultValue(value string) *CustomAttributeEnvironmentApplyConfiguration {
	b.DefaultValue = &value
	return b
}
