// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// DirectResponseSpecApplyConfiguration represents a declarative configuration of the DirectResponseSpec type for use
// with apply.
//
// DirectResponseSpec describes the desired state of a DirectResponse.
type DirectResponseSpecApplyConfiguration struct {
	// StatusCode defines the HTTP status code to return for this route.
	StatusCode *int32 `json:"status,omitempty"`
	// Body defines the content to be returned in the HTTP response body.
	// The maximum length of the body is restricted to prevent excessively large responses.
	// If this field is omitted, no body is included in the response.
	Body *string `json:"body,omitempty"`
}

// DirectResponseSpecApplyConfiguration constructs a declarative configuration of the DirectResponseSpec type for use with
// apply.
func DirectResponseSpec() *DirectResponseSpecApplyConfiguration {
	return &DirectResponseSpecApplyConfiguration{}
}

// WithStatusCode sets the StatusCode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StatusCode field is set to the value of the last call.
func (b *DirectResponseSpecApplyConfiguration) WithStatusCode(value int32) *DirectResponseSpecApplyConfiguration {
	b.StatusCode = &value
	return b
}

// WithBody sets the Body field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Body field is set to the value of the last call.
func (b *DirectResponseSpecApplyConfiguration) WithBody(value string) *DirectResponseSpecApplyConfiguration {
	b.Body = &value
	return b
}
