// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/kgateway-dev/kgateway/v2/api/v1alpha1"
)

// ExtAuthPolicyApplyConfiguration represents a declarative configuration of the ExtAuthPolicy type for use
// with apply.
//
// ExtAuthPolicy configures external authentication/authorization for a route.
// This policy will determine the ext auth server to use and how to talk to it.
// Note that most of these fields are passed along as is to Envoy.
// For more details on particular fields please see the Envoy ExtAuth documentation.
// https://raw.githubusercontent.com/envoyproxy/envoy/f910f4abea24904aff04ec33a00147184ea7cffa/api/envoy/extensions/filters/http/ext_authz/v3/ext_authz.proto
type ExtAuthPolicyApplyConfiguration struct {
	// ExtensionRef references the GatewayExtension that should be used for auth.
	ExtensionRef *NamespacedObjectReferenceApplyConfiguration `json:"extensionRef,omitempty"`
	// WithRequestBody allows the request body to be buffered and sent to the auth service.
	// Warning buffering has implications for streaming and therefore performance.
	WithRequestBody *ExtAuthBufferSettingsApplyConfiguration `json:"withRequestBody,omitempty"`
	// Additional context for the auth service.
	ContextExtensions map[string]string `json:"contextExtensions,omitempty"`
	// Disable all external auth filters.
	// Can be used to disable external auth policies applied at a higher level in the config hierarchy.
	Disable *apiv1alpha1.PolicyDisable `json:"disable,omitempty"`
}

// ExtAuthPolicyApplyConfiguration constructs a declarative configuration of the ExtAuthPolicy type for use with
// apply.
func ExtAuthPolicy() *ExtAuthPolicyApplyConfiguration {
	return &ExtAuthPolicyApplyConfiguration{}
}

// WithExtensionRef sets the ExtensionRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ExtensionRef field is set to the value of the last call.
func (b *ExtAuthPolicyApplyConfiguration) WithExtensionRef(value *NamespacedObjectReferenceApplyConfiguration) *ExtAuthPolicyApplyConfiguration {
	b.ExtensionRef = value
	return b
}

// WithWithRequestBody sets the WithRequestBody field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WithRequestBody field is set to the value of the last call.
func (b *ExtAuthPolicyApplyConfiguration) WithWithRequestBody(value *ExtAuthBufferSettingsApplyConfiguration) *ExtAuthPolicyApplyConfiguration {
	b.WithRequestBody = value
	return b
}

// WithContextExtensions puts the entries into the ContextExtensions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the ContextExtensions field,
// overwriting an existing map entries in ContextExtensions field with the same key.
func (b *ExtAuthPolicyApplyConfiguration) WithContextExtensions(entries map[string]string) *ExtAuthPolicyApplyConfiguration {
	if b.ContextExtensions == nil && len(entries) > 0 {
		b.ContextExtensions = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ContextExtensions[k] = v
	}
	return b
}

// WithDisable sets the Disable field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Disable field is set to the value of the last call.
func (b *ExtAuthPolicyApplyConfiguration) WithDisable(value apiv1alpha1.PolicyDisable) *ExtAuthPolicyApplyConfiguration {
	b.Disable = &value
	return b
}
