// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ExtAuthProviderApplyConfiguration represents a declarative configuration of the ExtAuthProvider type for use
// with apply.
//
// ExtAuthProvider defines the configuration for an ExtAuth provider.
type ExtAuthProviderApplyConfiguration struct {
	// GrpcService is the GRPC service that will handle the auth.
	GrpcService *ExtGrpcServiceApplyConfiguration `json:"grpcService,omitempty"`
	// FailOpen determines if requests are allowed when the ext auth service is unavailable.
	// Defaults to false, meaning requests will be denied if the ext auth service is unavailable.
	FailOpen *bool `json:"failOpen,omitempty"`
	// ClearRouteCache determines if the route cache should be cleared to allow the
	// external authentication service to correctly affect routing decisions.
	ClearRouteCache *bool `json:"clearRouteCache,omitempty"`
	// WithRequestBody allows the request body to be buffered and sent to the auth service.
	// Warning: buffering has implications for streaming and therefore performance.
	WithRequestBody *ExtAuthBufferSettingsApplyConfiguration `json:"withRequestBody,omitempty"`
	// StatusOnError sets the HTTP status response code that is returned to the client when the
	// auth server returns an error or cannot be reached. Must be in the range of 100-511 inclusive.
	// The default matches the deny response code of 403 Forbidden.
	StatusOnError *int32 `json:"statusOnError,omitempty"`
	// StatPrefix is an optional prefix to include when emitting stats from the extauthz filter,
	// enabling different instances of the filter to have unique stats.
	StatPrefix *string `json:"statPrefix,omitempty"`
}

// ExtAuthProviderApplyConfiguration constructs a declarative configuration of the ExtAuthProvider type for use with
// apply.
func ExtAuthProvider() *ExtAuthProviderApplyConfiguration {
	return &ExtAuthProviderApplyConfiguration{}
}

// WithGrpcService sets the GrpcService field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GrpcService field is set to the value of the last call.
func (b *ExtAuthProviderApplyConfiguration) WithGrpcService(value *ExtGrpcServiceApplyConfiguration) *ExtAuthProviderApplyConfiguration {
	b.GrpcService = value
	return b
}

// WithFailOpen sets the FailOpen field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FailOpen field is set to the value of the last call.
func (b *ExtAuthProviderApplyConfiguration) WithFailOpen(value bool) *ExtAuthProviderApplyConfiguration {
	b.FailOpen = &value
	return b
}

// WithClearRouteCache sets the ClearRouteCache field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClearRouteCache field is set to the value of the last call.
func (b *ExtAuthProviderApplyConfiguration) WithClearRouteCache(value bool) *ExtAuthProviderApplyConfiguration {
	b.ClearRouteCache = &value
	return b
}

// WithWithRequestBody sets the WithRequestBody field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WithRequestBody field is set to the value of the last call.
func (b *ExtAuthProviderApplyConfiguration) WithWithRequestBody(value *ExtAuthBufferSettingsApplyConfiguration) *ExtAuthProviderApplyConfiguration {
	b.WithRequestBody = value
	return b
}

// WithStatusOnError sets the StatusOnError field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StatusOnError field is set to the value of the last call.
func (b *ExtAuthProviderApplyConfiguration) WithStatusOnError(value int32) *ExtAuthProviderApplyConfiguration {
	b.StatusOnError = &value
	return b
}

// WithStatPrefix sets the StatPrefix field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StatPrefix field is set to the value of the last call.
func (b *ExtAuthProviderApplyConfiguration) WithStatPrefix(value string) *ExtAuthProviderApplyConfiguration {
	b.StatPrefix = &value
	return b
}
