// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ExtAuthBufferSettingsApplyConfiguration represents a declarative configuration of the ExtAuthBufferSettings type for use
// with apply.
//
// ExtAuthBufferSettings configures how the request body should be buffered.
type ExtAuthBufferSettingsApplyConfiguration struct {
	// MaxRequestBytes sets the maximum size of a message body to buffer.
	// Requests exceeding this size will receive HTTP 413 and not be sent to the auth service.
	MaxRequestBytes *int32 `json:"maxRequestBytes,omitempty"`
	// AllowPartialMessage determines if partial messages should be allowed.
	// When true, requests will be sent to the auth service even if they exceed maxRequestBytes.
	// The default behavior is false.
	AllowPartialMessage *bool `json:"allowPartialMessage,omitempty"`
	// PackAsBytes determines if the body should be sent as raw bytes.
	// When true, the body is sent as raw bytes in the raw_body field.
	// When false, the body is sent as UTF-8 string in the body field.
	// The default behavior is false.
	PackAsBytes *bool `json:"packAsBytes,omitempty"`
}

// ExtAuthBufferSettingsApplyConfiguration constructs a declarative configuration of the ExtAuthBufferSettings type for use with
// apply.
func ExtAuthBufferSettings() *ExtAuthBufferSettingsApplyConfiguration {
	return &ExtAuthBufferSettingsApplyConfiguration{}
}

// WithMaxRequestBytes sets the MaxRequestBytes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxRequestBytes field is set to the value of the last call.
func (b *ExtAuthBufferSettingsApplyConfiguration) WithMaxRequestBytes(value int32) *ExtAuthBufferSettingsApplyConfiguration {
	b.MaxRequestBytes = &value
	return b
}

// WithAllowPartialMessage sets the AllowPartialMessage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AllowPartialMessage field is set to the value of the last call.
func (b *ExtAuthBufferSettingsApplyConfiguration) WithAllowPartialMessage(value bool) *ExtAuthBufferSettingsApplyConfiguration {
	b.AllowPartialMessage = &value
	return b
}

// WithPackAsBytes sets the PackAsBytes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PackAsBytes field is set to the value of the last call.
func (b *ExtAuthBufferSettingsApplyConfiguration) WithPackAsBytes(value bool) *ExtAuthBufferSettingsApplyConfiguration {
	b.PackAsBytes = &value
	return b
}
