// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	apiv1alpha1 "github.com/kgateway-dev/kgateway/v2/api/v1alpha1"
)

// ExtProcProviderApplyConfiguration represents a declarative configuration of the ExtProcProvider type for use
// with apply.
//
// ExtProcProvider defines the configuration for an ExtProc provider.
type ExtProcProviderApplyConfiguration struct {
	// GrpcService is the GRPC service that will handle the processing.
	GrpcService *ExtGrpcServiceApplyConfiguration `json:"grpcService,omitempty"`
	// FailOpen determines if requests are allowed when the ext proc service is unavailable.
	// Defaults to true, meaning requests are allowed upstream even if the ext proc service is unavailable.
	FailOpen *bool `json:"failOpen,omitempty"`
	// ProcessingMode defines how the filter should interact with the request/response streams.
	ProcessingMode *ProcessingModeApplyConfiguration `json:"processingMode,omitempty"`
	// MessageTimeout is the timeout for each message sent to the external processing server.
	MessageTimeout *v1.Duration `json:"messageTimeout,omitempty"`
	// MaxMessageTimeout specifies the upper bound of override_message_timeout that may be sent from the external processing server.
	// The default value 0, which effectively disables the override_message_timeout API.
	MaxMessageTimeout *v1.Duration `json:"maxMessageTimeout,omitempty"`
	// StatPrefix is an optional prefix to include when emitting stats from the extproc filter,
	// enabling different instances of the filter to have unique stats.
	StatPrefix *string `json:"statPrefix,omitempty"`
	// RouteCacheAction describes the route cache action to be taken when an
	// external processor response is received in response to request headers.
	// The default behavior is "FromResponse" which will only clear the route cache when
	// an external processing response has the clear_route_cache field set.
	RouteCacheAction *apiv1alpha1.ExtProcRouteCacheAction `json:"routeCacheAction,omitempty"`
	// MetadataOptions allows configuring metadata namespaces to forwarded or received from the external
	// processing server.
	MetadataOptions *MetadataOptionsApplyConfiguration `json:"metadataOptions,omitempty"`
}

// ExtProcProviderApplyConfiguration constructs a declarative configuration of the ExtProcProvider type for use with
// apply.
func ExtProcProvider() *ExtProcProviderApplyConfiguration {
	return &ExtProcProviderApplyConfiguration{}
}

// WithGrpcService sets the GrpcService field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GrpcService field is set to the value of the last call.
func (b *ExtProcProviderApplyConfiguration) WithGrpcService(value *ExtGrpcServiceApplyConfiguration) *ExtProcProviderApplyConfiguration {
	b.GrpcService = value
	return b
}

// WithFailOpen sets the FailOpen field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FailOpen field is set to the value of the last call.
func (b *ExtProcProviderApplyConfiguration) WithFailOpen(value bool) *ExtProcProviderApplyConfiguration {
	b.FailOpen = &value
	return b
}

// WithProcessingMode sets the ProcessingMode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProcessingMode field is set to the value of the last call.
func (b *ExtProcProviderApplyConfiguration) WithProcessingMode(value *ProcessingModeApplyConfiguration) *ExtProcProviderApplyConfiguration {
	b.ProcessingMode = value
	return b
}

// WithMessageTimeout sets the MessageTimeout field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MessageTimeout field is set to the value of the last call.
func (b *ExtProcProviderApplyConfiguration) WithMessageTimeout(value v1.Duration) *ExtProcProviderApplyConfiguration {
	b.MessageTimeout = &value
	return b
}

// WithMaxMessageTimeout sets the MaxMessageTimeout field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxMessageTimeout field is set to the value of the last call.
func (b *ExtProcProviderApplyConfiguration) WithMaxMessageTimeout(value v1.Duration) *ExtProcProviderApplyConfiguration {
	b.MaxMessageTimeout = &value
	return b
}

// WithStatPrefix sets the StatPrefix field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StatPrefix field is set to the value of the last call.
func (b *ExtProcProviderApplyConfiguration) WithStatPrefix(value string) *ExtProcProviderApplyConfiguration {
	b.StatPrefix = &value
	return b
}

// WithRouteCacheAction sets the RouteCacheAction field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RouteCacheAction field is set to the value of the last call.
func (b *ExtProcProviderApplyConfiguration) WithRouteCacheAction(value apiv1alpha1.ExtProcRouteCacheAction) *ExtProcProviderApplyConfiguration {
	b.RouteCacheAction = &value
	return b
}

// WithMetadataOptions sets the MetadataOptions field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MetadataOptions field is set to the value of the last call.
func (b *ExtProcProviderApplyConfiguration) WithMetadataOptions(value *MetadataOptionsApplyConfiguration) *ExtProcProviderApplyConfiguration {
	b.MetadataOptions = value
	return b
}
