// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/kgateway-dev/kgateway/v2/api/v1alpha1"
)

// ExtProcPolicyApplyConfiguration represents a declarative configuration of the ExtProcPolicy type for use
// with apply.
//
// ExtProcPolicy defines the configuration for the Envoy External Processing filter.
type ExtProcPolicyApplyConfiguration struct {
	// ExtensionRef references the GatewayExtension that should be used for external processing.
	ExtensionRef *NamespacedObjectReferenceApplyConfiguration `json:"extensionRef,omitempty"`
	// ProcessingMode defines how the filter should interact with the request/response streams
	ProcessingMode *ProcessingModeApplyConfiguration `json:"processingMode,omitempty"`
	// Disable all external processing filters.
	// Can be used to disable external processing policies applied at a higher level in the config hierarchy.
	Disable *apiv1alpha1.PolicyDisable `json:"disable,omitempty"`
}

// ExtProcPolicyApplyConfiguration constructs a declarative configuration of the ExtProcPolicy type for use with
// apply.
func ExtProcPolicy() *ExtProcPolicyApplyConfiguration {
	return &ExtProcPolicyApplyConfiguration{}
}

// WithExtensionRef sets the ExtensionRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ExtensionRef field is set to the value of the last call.
func (b *ExtProcPolicyApplyConfiguration) WithExtensionRef(value *NamespacedObjectReferenceApplyConfiguration) *ExtProcPolicyApplyConfiguration {
	b.ExtensionRef = value
	return b
}

// WithProcessingMode sets the ProcessingMode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProcessingMode field is set to the value of the last call.
func (b *ExtProcPolicyApplyConfiguration) WithProcessingMode(value *ProcessingModeApplyConfiguration) *ExtProcPolicyApplyConfiguration {
	b.ProcessingMode = value
	return b
}

// WithDisable sets the Disable field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Disable field is set to the value of the last call.
func (b *ExtProcPolicyApplyConfiguration) WithDisable(value apiv1alpha1.PolicyDisable) *ExtProcPolicyApplyConfiguration {
	b.Disable = &value
	return b
}
