// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// FieldDefaultApplyConfiguration represents a declarative configuration of the FieldDefault type for use
// with apply.
//
// FieldDefault provides default values for specific fields in the JSON request body sent to the LLM provider.
// These defaults are merged with the user-provided request to ensure missing fields are populated.
//
// User input fields here refer to the fields in the JSON request body that a client sends when making a request to the LLM provider.
// Defaults set here do _not_ override those user-provided values unless you explicitly set `override` to `true`.
//
// Example: Setting a default system field for Anthropic, which does not support system role messages:
// ```yaml
// defaults:
// - field: "system"
// value: "answer all questions in French"
//
// ```
//
// Example: Setting a default temperature and overriding `max_tokens`:
// ```yaml
// defaults:
// - field: "temperature"
// value: "0.5"
// - field: "max_tokens"
// value: "100"
// override: true
//
// ```
//
// Example: Setting custom lists fields:
// ```yaml
// defaults:
// - field: "custom_integer_list"
// value: "[1,2,3]"
// - field: "custom_string_list"
// value: '["one","two","three"]'
// override: true
//
// ```
//
// Note: The `field` values correspond to keys in the JSON request body, not fields in this CRD.
type FieldDefaultApplyConfiguration struct {
	// The name of the field.
	Field *string `json:"field,omitempty"`
	// The field default value, which can be any JSON Data Type.
	Value *string `json:"value,omitempty"`
	// Whether to override the field's value if it already exists.
	// Defaults to false.
	Override *bool `json:"override,omitempty"`
}

// FieldDefaultApplyConfiguration constructs a declarative configuration of the FieldDefault type for use with
// apply.
func FieldDefault() *FieldDefaultApplyConfiguration {
	return &FieldDefaultApplyConfiguration{}
}

// WithField sets the Field field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Field field is set to the value of the last call.
func (b *FieldDefaultApplyConfiguration) WithField(value string) *FieldDefaultApplyConfiguration {
	b.Field = &value
	return b
}

// WithValue sets the Value field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Value field is set to the value of the last call.
func (b *FieldDefaultApplyConfiguration) WithValue(value string) *FieldDefaultApplyConfiguration {
	b.Value = &value
	return b
}

// WithOverride sets the Override field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Override field is set to the value of the last call.
func (b *FieldDefaultApplyConfiguration) WithOverride(value bool) *FieldDefaultApplyConfiguration {
	b.Override = &value
	return b
}
