// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "sigs.k8s.io/gateway-api/apis/v1"
)

// HeaderModifiersApplyConfiguration represents a declarative configuration of the HeaderModifiers type for use
// with apply.
//
// HeaderModifiers can be used to define the policy to modify request and response headers.
type HeaderModifiersApplyConfiguration struct {
	// Request modifies request headers.
	Request *v1.HTTPHeaderFilter `json:"request,omitempty"`
	// Response modifies response headers.
	Response *v1.HTTPHeaderFilter `json:"response,omitempty"`
}

// HeaderModifiersApplyConfiguration constructs a declarative configuration of the HeaderModifiers type for use with
// apply.
func HeaderModifiers() *HeaderModifiersApplyConfiguration {
	return &HeaderModifiersApplyConfiguration{}
}

// WithRequest sets the Request field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Request field is set to the value of the last call.
func (b *HeaderModifiersApplyConfiguration) WithRequest(value v1.HTTPHeaderFilter) *HeaderModifiersApplyConfiguration {
	b.Request = &value
	return b
}

// WithResponse sets the Response field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Response field is set to the value of the last call.
func (b *HeaderModifiersApplyConfiguration) WithResponse(value v1.HTTPHeaderFilter) *HeaderModifiersApplyConfiguration {
	b.Response = &value
	return b
}
