// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// HealthCheckApplyConfiguration represents a declarative configuration of the HealthCheck type for use
// with apply.
//
// HealthCheck contains the options to configure the health check.
// See [Envoy documentation](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/health_check.proto) for more details.
type HealthCheckApplyConfiguration struct {
	// Timeout is time to wait for a health check response. If the timeout is reached the
	// health check attempt will be considered a failure.
	Timeout *v1.Duration `json:"timeout,omitempty"`
	// Interval is the time between health checks.
	Interval *v1.Duration `json:"interval,omitempty"`
	// UnhealthyThreshold is the number of consecutive failed health checks that will be considered
	// unhealthy.
	// Note that for HTTP health checks, if a host responds with a code not in ExpectedStatuses or RetriableStatuses,
	// this threshold is ignored and the host is considered immediately unhealthy.
	UnhealthyThreshold *int32 `json:"unhealthyThreshold,omitempty"`
	// HealthyThreshold is the number of healthy health checks required before a host is marked
	// healthy. Note that during startup, only a single successful health check is
	// required to mark a host healthy.
	HealthyThreshold *int32 `json:"healthyThreshold,omitempty"`
	// Http contains the options to configure the HTTP health check.
	Http *HealthCheckHttpApplyConfiguration `json:"http,omitempty"`
	// Grpc contains the options to configure the gRPC health check.
	Grpc *HealthCheckGrpcApplyConfiguration `json:"grpc,omitempty"`
}

// HealthCheckApplyConfiguration constructs a declarative configuration of the HealthCheck type for use with
// apply.
func HealthCheck() *HealthCheckApplyConfiguration {
	return &HealthCheckApplyConfiguration{}
}

// WithTimeout sets the Timeout field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Timeout field is set to the value of the last call.
func (b *HealthCheckApplyConfiguration) WithTimeout(value v1.Duration) *HealthCheckApplyConfiguration {
	b.Timeout = &value
	return b
}

// WithInterval sets the Interval field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Interval field is set to the value of the last call.
func (b *HealthCheckApplyConfiguration) WithInterval(value v1.Duration) *HealthCheckApplyConfiguration {
	b.Interval = &value
	return b
}

// WithUnhealthyThreshold sets the UnhealthyThreshold field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UnhealthyThreshold field is set to the value of the last call.
func (b *HealthCheckApplyConfiguration) WithUnhealthyThreshold(value int32) *HealthCheckApplyConfiguration {
	b.UnhealthyThreshold = &value
	return b
}

// WithHealthyThreshold sets the HealthyThreshold field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HealthyThreshold field is set to the value of the last call.
func (b *HealthCheckApplyConfiguration) WithHealthyThreshold(value int32) *HealthCheckApplyConfiguration {
	b.HealthyThreshold = &value
	return b
}

// WithHttp sets the Http field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Http field is set to the value of the last call.
func (b *HealthCheckApplyConfiguration) WithHttp(value *HealthCheckHttpApplyConfiguration) *HealthCheckApplyConfiguration {
	b.Http = value
	return b
}

// WithGrpc sets the Grpc field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Grpc field is set to the value of the last call.
func (b *HealthCheckApplyConfiguration) WithGrpc(value *HealthCheckGrpcApplyConfiguration) *HealthCheckApplyConfiguration {
	b.Grpc = value
	return b
}
