// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// Http1ProtocolOptionsApplyConfiguration represents a declarative configuration of the Http1ProtocolOptions type for use
// with apply.
//
// See [Envoy documentation](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/protocol.proto#envoy-v3-api-msg-config-core-v3-http1protocoloptions) for more details.
type Http1ProtocolOptionsApplyConfiguration struct {
	// Enables trailers for HTTP/1. By default the HTTP/1 codec drops proxied trailers.
	// Note: Trailers must also be enabled at the gateway level in order for this option to take effect
	EnableTrailers *bool `json:"enableTrailers,omitempty"`
	// PreserveHttp1HeaderCase determines whether to preserve the case of HTTP1 response headers.
	// See here for more information: https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/header_casing
	PreserveHttp1HeaderCase *bool `json:"preserveHttp1HeaderCase,omitempty"`
	// Allows invalid HTTP messaging. When this option is false, then Envoy will terminate
	// HTTP/1.1 connections upon receiving an invalid HTTP message. However,
	// when this option is true, then Envoy will leave the HTTP/1.1 connection
	// open where possible.
	OverrideStreamErrorOnInvalidHttpMessage *bool `json:"overrideStreamErrorOnInvalidHttpMessage,omitempty"`
}

// Http1ProtocolOptionsApplyConfiguration constructs a declarative configuration of the Http1ProtocolOptions type for use with
// apply.
func Http1ProtocolOptions() *Http1ProtocolOptionsApplyConfiguration {
	return &Http1ProtocolOptionsApplyConfiguration{}
}

// WithEnableTrailers sets the EnableTrailers field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EnableTrailers field is set to the value of the last call.
func (b *Http1ProtocolOptionsApplyConfiguration) WithEnableTrailers(value bool) *Http1ProtocolOptionsApplyConfiguration {
	b.EnableTrailers = &value
	return b
}

// WithPreserveHttp1HeaderCase sets the PreserveHttp1HeaderCase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PreserveHttp1HeaderCase field is set to the value of the last call.
func (b *Http1ProtocolOptionsApplyConfiguration) WithPreserveHttp1HeaderCase(value bool) *Http1ProtocolOptionsApplyConfiguration {
	b.PreserveHttp1HeaderCase = &value
	return b
}

// WithOverrideStreamErrorOnInvalidHttpMessage sets the OverrideStreamErrorOnInvalidHttpMessage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OverrideStreamErrorOnInvalidHttpMessage field is set to the value of the last call.
func (b *Http1ProtocolOptionsApplyConfiguration) WithOverrideStreamErrorOnInvalidHttpMessage(value bool) *Http1ProtocolOptionsApplyConfiguration {
	b.OverrideStreamErrorOnInvalidHttpMessage = &value
	return b
}
