// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	apiv1alpha1 "github.com/kgateway-dev/kgateway/v2/api/v1alpha1"
)

// HTTPListenerPolicySpecApplyConfiguration represents a declarative configuration of the HTTPListenerPolicySpec type for use
// with apply.
//
// HTTPListenerPolicySpec defines the desired state of a HTTP listener policy.
type HTTPListenerPolicySpecApplyConfiguration struct {
	// TargetRefs specifies the target resources by reference to attach the policy to.
	TargetRefs []LocalPolicyTargetReferenceApplyConfiguration `json:"targetRefs,omitempty"`
	// TargetSelectors specifies the target selectors to select resources to attach the policy to.
	TargetSelectors []LocalPolicyTargetSelectorApplyConfiguration `json:"targetSelectors,omitempty"`
	// AccessLoggingConfig contains various settings for Envoy's access logging service.
	// See here for more information: https://www.envoyproxy.io/docs/envoy/v1.33.0/api-v3/config/accesslog/v3/accesslog.proto
	AccessLog []AccessLogApplyConfiguration `json:"accessLog,omitempty"`
	// Tracing contains various settings for Envoy's OpenTelemetry tracer.
	// See here for more information: https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/trace/v3/opentelemetry.proto.html
	Tracing *TracingApplyConfiguration `json:"tracing,omitempty"`
	// UpgradeConfig contains configuration for HTTP upgrades like WebSocket.
	// See here for more information: https://www.envoyproxy.io/docs/envoy/v1.34.1/intro/arch_overview/http/upgrades.html
	UpgradeConfig *UpgradeConfigApplyConfiguration `json:"upgradeConfig,omitempty"`
	// UseRemoteAddress determines whether to use the remote address for the original client.
	// Note: If this field is omitted, it will fallback to the default value of 'true', which we set for all Envoy HCMs.
	// Thus, setting this explicitly to true is unnecessary (but will not cause any harm).
	// When true, Envoy will use the remote address of the connection as the client address.
	// When false, Envoy will use the X-Forwarded-For header to determine the client address.
	// See here for more information: https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#envoy-v3-api-field-extensions-filters-network-http-connection-manager-v3-httpconnectionmanager-use-remote-address
	UseRemoteAddress *bool `json:"useRemoteAddress,omitempty"`
	// XffNumTrustedHops is the number of additional ingress proxy hops from the right side of the X-Forwarded-For HTTP header to trust when determining the origin client's IP address.
	// See here for more information: https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#envoy-v3-api-field-extensions-filters-network-http-connection-manager-v3-httpconnectionmanager-xff-num-trusted-hops
	XffNumTrustedHops *int32 `json:"xffNumTrustedHops,omitempty"`
	// ServerHeaderTransformation determines how the server header is transformed.
	// See here for more information: https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#envoy-v3-api-field-extensions-filters-network-http-connection-manager-v3-httpconnectionmanager-server-header-transformation
	ServerHeaderTransformation *apiv1alpha1.ServerHeaderTransformation `json:"serverHeaderTransformation,omitempty"`
	// StreamIdleTimeout is the idle timeout for HTTP streams.
	// See here for more information: https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#envoy-v3-api-field-extensions-filters-network-http-connection-manager-v3-httpconnectionmanager-stream-idle-timeout
	StreamIdleTimeout *v1.Duration `json:"streamIdleTimeout,omitempty"`
	// IdleTimeout is the idle timeout for connnections.
	// See here for more information: https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/protocol.proto#envoy-v3-api-msg-config-core-v3-httpprotocoloptions
	IdleTimeout *v1.Duration `json:"idleTimeout,omitempty"`
	// HealthCheck configures [Envoy health checks](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/health_check/v3/health_check.proto)
	HealthCheck *EnvoyHealthCheckApplyConfiguration `json:"healthCheck,omitempty"`
	// PreserveHttp1HeaderCase determines whether to preserve the case of HTTP1 request headers.
	// See here for more information: https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/header_casing
	PreserveHttp1HeaderCase *bool `json:"preserveHttp1HeaderCase,omitempty"`
	// AcceptHTTP10 determines whether to accept incoming HTTP/1.0 and HTTP 0.9 requests.
	// See here for more information: https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/protocol.proto#config-core-v3-http1protocoloptions
	AcceptHttp10 *bool `json:"acceptHttp10,omitempty"`
	// DefaultHostForHttp10 specifies a default host for HTTP/1.0 requests. This is highly suggested if acceptHttp10 is true and a no-op if acceptHttp10 is false.
	// See here for more information: https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/protocol.proto#config-core-v3-http1protocoloptions
	DefaultHostForHttp10 *string `json:"defaultHostForHttp10,omitempty"`
}

// HTTPListenerPolicySpecApplyConfiguration constructs a declarative configuration of the HTTPListenerPolicySpec type for use with
// apply.
func HTTPListenerPolicySpec() *HTTPListenerPolicySpecApplyConfiguration {
	return &HTTPListenerPolicySpecApplyConfiguration{}
}

// WithTargetRefs adds the given value to the TargetRefs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the TargetRefs field.
func (b *HTTPListenerPolicySpecApplyConfiguration) WithTargetRefs(values ...*LocalPolicyTargetReferenceApplyConfiguration) *HTTPListenerPolicySpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithTargetRefs")
		}
		b.TargetRefs = append(b.TargetRefs, *values[i])
	}
	return b
}

// WithTargetSelectors adds the given value to the TargetSelectors field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the TargetSelectors field.
func (b *HTTPListenerPolicySpecApplyConfiguration) WithTargetSelectors(values ...*LocalPolicyTargetSelectorApplyConfiguration) *HTTPListenerPolicySpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithTargetSelectors")
		}
		b.TargetSelectors = append(b.TargetSelectors, *values[i])
	}
	return b
}

// WithAccessLog adds the given value to the AccessLog field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AccessLog field.
func (b *HTTPListenerPolicySpecApplyConfiguration) WithAccessLog(values ...*AccessLogApplyConfiguration) *HTTPListenerPolicySpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithAccessLog")
		}
		b.AccessLog = append(b.AccessLog, *values[i])
	}
	return b
}

// WithTracing sets the Tracing field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Tracing field is set to the value of the last call.
func (b *HTTPListenerPolicySpecApplyConfiguration) WithTracing(value *TracingApplyConfiguration) *HTTPListenerPolicySpecApplyConfiguration {
	b.Tracing = value
	return b
}

// WithUpgradeConfig sets the UpgradeConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UpgradeConfig field is set to the value of the last call.
func (b *HTTPListenerPolicySpecApplyConfiguration) WithUpgradeConfig(value *UpgradeConfigApplyConfiguration) *HTTPListenerPolicySpecApplyConfiguration {
	b.UpgradeConfig = value
	return b
}

// WithUseRemoteAddress sets the UseRemoteAddress field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UseRemoteAddress field is set to the value of the last call.
func (b *HTTPListenerPolicySpecApplyConfiguration) WithUseRemoteAddress(value bool) *HTTPListenerPolicySpecApplyConfiguration {
	b.UseRemoteAddress = &value
	return b
}

// WithXffNumTrustedHops sets the XffNumTrustedHops field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the XffNumTrustedHops field is set to the value of the last call.
func (b *HTTPListenerPolicySpecApplyConfiguration) WithXffNumTrustedHops(value int32) *HTTPListenerPolicySpecApplyConfiguration {
	b.XffNumTrustedHops = &value
	return b
}

// WithServerHeaderTransformation sets the ServerHeaderTransformation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServerHeaderTransformation field is set to the value of the last call.
func (b *HTTPListenerPolicySpecApplyConfiguration) WithServerHeaderTransformation(value apiv1alpha1.ServerHeaderTransformation) *HTTPListenerPolicySpecApplyConfiguration {
	b.ServerHeaderTransformation = &value
	return b
}

// WithStreamIdleTimeout sets the StreamIdleTimeout field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StreamIdleTimeout field is set to the value of the last call.
func (b *HTTPListenerPolicySpecApplyConfiguration) WithStreamIdleTimeout(value v1.Duration) *HTTPListenerPolicySpecApplyConfiguration {
	b.StreamIdleTimeout = &value
	return b
}

// WithIdleTimeout sets the IdleTimeout field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IdleTimeout field is set to the value of the last call.
func (b *HTTPListenerPolicySpecApplyConfiguration) WithIdleTimeout(value v1.Duration) *HTTPListenerPolicySpecApplyConfiguration {
	b.IdleTimeout = &value
	return b
}

// WithHealthCheck sets the HealthCheck field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HealthCheck field is set to the value of the last call.
func (b *HTTPListenerPolicySpecApplyConfiguration) WithHealthCheck(value *EnvoyHealthCheckApplyConfiguration) *HTTPListenerPolicySpecApplyConfiguration {
	b.HealthCheck = value
	return b
}

// WithPreserveHttp1HeaderCase sets the PreserveHttp1HeaderCase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PreserveHttp1HeaderCase field is set to the value of the last call.
func (b *HTTPListenerPolicySpecApplyConfiguration) WithPreserveHttp1HeaderCase(value bool) *HTTPListenerPolicySpecApplyConfiguration {
	b.PreserveHttp1HeaderCase = &value
	return b
}

// WithAcceptHttp10 sets the AcceptHttp10 field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AcceptHttp10 field is set to the value of the last call.
func (b *HTTPListenerPolicySpecApplyConfiguration) WithAcceptHttp10(value bool) *HTTPListenerPolicySpecApplyConfiguration {
	b.AcceptHttp10 = &value
	return b
}

// WithDefaultHostForHttp10 sets the DefaultHostForHttp10 field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DefaultHostForHttp10 field is set to the value of the last call.
func (b *HTTPListenerPolicySpecApplyConfiguration) WithDefaultHostForHttp10(value string) *HTTPListenerPolicySpecApplyConfiguration {
	b.DefaultHostForHttp10 = &value
	return b
}
