// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// KeyAnyValueApplyConfiguration represents a declarative configuration of the KeyAnyValue type for use
// with apply.
//
// KeyValue is a key-value pair that is used to store Span attributes, Link attributes, etc.
type KeyAnyValueApplyConfiguration struct {
	// Attribute keys must be unique
	Key *string `json:"key,omitempty"`
	// Value may contain a primitive value such as a string or integer or it may contain an arbitrary nested object containing arrays, key-value lists and primitives.
	Value *AnyValueApplyConfiguration `json:"value,omitempty"`
}

// KeyAnyValueApplyConfiguration constructs a declarative configuration of the KeyAnyValue type for use with
// apply.
func KeyAnyValue() *KeyAnyValueApplyConfiguration {
	return &KeyAnyValueApplyConfiguration{}
}

// WithKey sets the Key field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Key field is set to the value of the last call.
func (b *KeyAnyValueApplyConfiguration) WithKey(value string) *KeyAnyValueApplyConfiguration {
	b.Key = &value
	return b
}

// WithValue sets the Value field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Value field is set to the value of the last call.
func (b *KeyAnyValueApplyConfiguration) WithValue(value *AnyValueApplyConfiguration) *KeyAnyValueApplyConfiguration {
	b.Value = value
	return b
}
