// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// KubernetesProxyConfigApplyConfiguration represents a declarative configuration of the KubernetesProxyConfig type for use
// with apply.
//
// KubernetesProxyConfig configures the set of Kubernetes resources that will be provisioned
// for a given Gateway.
type KubernetesProxyConfigApplyConfiguration struct {
	// Use a Kubernetes deployment as the proxy workload type. Currently, this is the only
	// supported workload type.
	Deployment *ProxyDeploymentApplyConfiguration `json:"deployment,omitempty"`
	// Configuration for the container running Envoy.
	// If agentgateway is enabled, the EnvoyContainer values will be ignored.
	EnvoyContainer *EnvoyContainerApplyConfiguration `json:"envoyContainer,omitempty"`
	// Configuration for the container running the Secret Discovery Service (SDS).
	SdsContainer *SdsContainerApplyConfiguration `json:"sdsContainer,omitempty"`
	// Configuration for the pods that will be created.
	PodTemplate *PodApplyConfiguration `json:"podTemplate,omitempty"`
	// Configuration for the Kubernetes Service that exposes the proxy over
	// the network.
	Service *ServiceApplyConfiguration `json:"service,omitempty"`
	// Configuration for the Kubernetes ServiceAccount used by the proxy pods.
	ServiceAccount *ServiceAccountApplyConfiguration `json:"serviceAccount,omitempty"`
	// Configuration for the Istio integration.
	Istio *IstioIntegrationApplyConfiguration `json:"istio,omitempty"`
	// Configuration for the stats server.
	Stats *StatsConfigApplyConfiguration `json:"stats,omitempty"`
	// Deprecated: `aiExtension` is deprecated in v2.1 and will be removed in v2.2.
	// Prefer to use `agentgateway` instead.
	//
	// Configuration for the AI extension.
	AiExtension *AiExtensionApplyConfiguration `json:"aiExtension,omitempty"`
	// Configure the agentgateway integration. If agentgateway is disabled, the
	// EnvoyContainer values will be used by default to configure the data
	// plane proxy.
	Agentgateway *AgentgatewayApplyConfiguration `json:"agentgateway,omitempty"`
	// Deprecated: Prefer to use omitDefaultSecurityContext instead. Will be
	// removed in the next release.
	//
	// Used to unset the `runAsUser` values in security contexts.
	FloatingUserId *bool `json:"floatingUserId,omitempty"`
	// OmitDefaultSecurityContext is used to control whether or not
	// `securityContext` fields should be rendered for the various generated
	// Deployments/Containers that are dynamically provisioned by the deployer.
	//
	// When set to true, no `securityContexts` will be provided and will left
	// to the user/platform to be provided.
	//
	// This should be enabled on platforms such as Red Hat OpenShift where the
	// `securityContext` will be dynamically added to enforce the appropriate
	// level of security.
	OmitDefaultSecurityContext *bool `json:"omitDefaultSecurityContext,omitempty"`
}

// KubernetesProxyConfigApplyConfiguration constructs a declarative configuration of the KubernetesProxyConfig type for use with
// apply.
func KubernetesProxyConfig() *KubernetesProxyConfigApplyConfiguration {
	return &KubernetesProxyConfigApplyConfiguration{}
}

// WithDeployment sets the Deployment field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Deployment field is set to the value of the last call.
func (b *KubernetesProxyConfigApplyConfiguration) WithDeployment(value *ProxyDeploymentApplyConfiguration) *KubernetesProxyConfigApplyConfiguration {
	b.Deployment = value
	return b
}

// WithEnvoyContainer sets the EnvoyContainer field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EnvoyContainer field is set to the value of the last call.
func (b *KubernetesProxyConfigApplyConfiguration) WithEnvoyContainer(value *EnvoyContainerApplyConfiguration) *KubernetesProxyConfigApplyConfiguration {
	b.EnvoyContainer = value
	return b
}

// WithSdsContainer sets the SdsContainer field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SdsContainer field is set to the value of the last call.
func (b *KubernetesProxyConfigApplyConfiguration) WithSdsContainer(value *SdsContainerApplyConfiguration) *KubernetesProxyConfigApplyConfiguration {
	b.SdsContainer = value
	return b
}

// WithPodTemplate sets the PodTemplate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodTemplate field is set to the value of the last call.
func (b *KubernetesProxyConfigApplyConfiguration) WithPodTemplate(value *PodApplyConfiguration) *KubernetesProxyConfigApplyConfiguration {
	b.PodTemplate = value
	return b
}

// WithService sets the Service field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Service field is set to the value of the last call.
func (b *KubernetesProxyConfigApplyConfiguration) WithService(value *ServiceApplyConfiguration) *KubernetesProxyConfigApplyConfiguration {
	b.Service = value
	return b
}

// WithServiceAccount sets the ServiceAccount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceAccount field is set to the value of the last call.
func (b *KubernetesProxyConfigApplyConfiguration) WithServiceAccount(value *ServiceAccountApplyConfiguration) *KubernetesProxyConfigApplyConfiguration {
	b.ServiceAccount = value
	return b
}

// WithIstio sets the Istio field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Istio field is set to the value of the last call.
func (b *KubernetesProxyConfigApplyConfiguration) WithIstio(value *IstioIntegrationApplyConfiguration) *KubernetesProxyConfigApplyConfiguration {
	b.Istio = value
	return b
}

// WithStats sets the Stats field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Stats field is set to the value of the last call.
func (b *KubernetesProxyConfigApplyConfiguration) WithStats(value *StatsConfigApplyConfiguration) *KubernetesProxyConfigApplyConfiguration {
	b.Stats = value
	return b
}

// WithAiExtension sets the AiExtension field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AiExtension field is set to the value of the last call.
func (b *KubernetesProxyConfigApplyConfiguration) WithAiExtension(value *AiExtensionApplyConfiguration) *KubernetesProxyConfigApplyConfiguration {
	b.AiExtension = value
	return b
}

// WithAgentgateway sets the Agentgateway field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Agentgateway field is set to the value of the last call.
func (b *KubernetesProxyConfigApplyConfiguration) WithAgentgateway(value *AgentgatewayApplyConfiguration) *KubernetesProxyConfigApplyConfiguration {
	b.Agentgateway = value
	return b
}

// WithFloatingUserId sets the FloatingUserId field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FloatingUserId field is set to the value of the last call.
func (b *KubernetesProxyConfigApplyConfiguration) WithFloatingUserId(value bool) *KubernetesProxyConfigApplyConfiguration {
	b.FloatingUserId = &value
	return b
}

// WithOmitDefaultSecurityContext sets the OmitDefaultSecurityContext field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OmitDefaultSecurityContext field is set to the value of the last call.
func (b *KubernetesProxyConfigApplyConfiguration) WithOmitDefaultSecurityContext(value bool) *KubernetesProxyConfigApplyConfiguration {
	b.OmitDefaultSecurityContext = &value
	return b
}
