// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	apiv1alpha1 "github.com/kgateway-dev/kgateway/v2/api/v1alpha1"
)

// LoadBalancerApplyConfiguration represents a declarative configuration of the LoadBalancer type for use
// with apply.
type LoadBalancerApplyConfiguration struct {
	// HealthyPanicThreshold configures envoy's panic threshold percentage between 0-100. Once the number of non-healthy hosts
	// reaches this percentage, envoy disregards health information.
	// See [Envoy documentation](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/panic_threshold.html).
	HealthyPanicThreshold *int32 `json:"healthyPanicThreshold,omitempty"`
	// This allows batch updates of endpoints health/weight/metadata that happen during a time window.
	// this help lower cpu usage when endpoint change rate is high. defaults to 1 second.
	// Set to 0 to disable and have changes applied immediately.
	UpdateMergeWindow *v1.Duration `json:"updateMergeWindow,omitempty"`
	// LeastRequest configures the least request load balancer type.
	LeastRequest *LoadBalancerLeastRequestConfigApplyConfiguration `json:"leastRequest,omitempty"`
	// RoundRobin configures the round robin load balancer type.
	RoundRobin *LoadBalancerRoundRobinConfigApplyConfiguration `json:"roundRobin,omitempty"`
	// RingHash configures the ring hash load balancer type.
	RingHash *LoadBalancerRingHashConfigApplyConfiguration `json:"ringHash,omitempty"`
	// Maglev configures the maglev load balancer type.
	Maglev *LoadBalancerMaglevConfigApplyConfiguration `json:"maglev,omitempty"`
	// Random configures the random load balancer type.
	Random *apiv1alpha1.LoadBalancerRandomConfig `json:"random,omitempty"`
	// LocalityType specifies the locality config type to use.
	// See https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/load_balancing_policies/common/v3/common.proto#envoy-v3-api-msg-extensions-load-balancing-policies-common-v3-localitylbconfig
	LocalityType *apiv1alpha1.LocalityType `json:"localityType,omitempty"`
	// If set to true, the load balancer will drain connections when the host set changes.
	//
	// Ring Hash or Maglev can be used to ensure that clients with the same key
	// are routed to the same upstream host.
	// Distruptions can cause new connections with the same key as existing connections
	// to be routed to different hosts.
	// Enabling this feature will cause the load balancer to drain existing connections
	// when the host set changes, ensuring that new connections with the same key are
	// consistently routed to the same host.
	// Connections are not immediately closed, but are allowed to drain
	// before being closed.
	CloseConnectionsOnHostSetChange *bool `json:"closeConnectionsOnHostSetChange,omitempty"`
}

// LoadBalancerApplyConfiguration constructs a declarative configuration of the LoadBalancer type for use with
// apply.
func LoadBalancer() *LoadBalancerApplyConfiguration {
	return &LoadBalancerApplyConfiguration{}
}

// WithHealthyPanicThreshold sets the HealthyPanicThreshold field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HealthyPanicThreshold field is set to the value of the last call.
func (b *LoadBalancerApplyConfiguration) WithHealthyPanicThreshold(value int32) *LoadBalancerApplyConfiguration {
	b.HealthyPanicThreshold = &value
	return b
}

// WithUpdateMergeWindow sets the UpdateMergeWindow field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UpdateMergeWindow field is set to the value of the last call.
func (b *LoadBalancerApplyConfiguration) WithUpdateMergeWindow(value v1.Duration) *LoadBalancerApplyConfiguration {
	b.UpdateMergeWindow = &value
	return b
}

// WithLeastRequest sets the LeastRequest field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LeastRequest field is set to the value of the last call.
func (b *LoadBalancerApplyConfiguration) WithLeastRequest(value *LoadBalancerLeastRequestConfigApplyConfiguration) *LoadBalancerApplyConfiguration {
	b.LeastRequest = value
	return b
}

// WithRoundRobin sets the RoundRobin field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RoundRobin field is set to the value of the last call.
func (b *LoadBalancerApplyConfiguration) WithRoundRobin(value *LoadBalancerRoundRobinConfigApplyConfiguration) *LoadBalancerApplyConfiguration {
	b.RoundRobin = value
	return b
}

// WithRingHash sets the RingHash field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RingHash field is set to the value of the last call.
func (b *LoadBalancerApplyConfiguration) WithRingHash(value *LoadBalancerRingHashConfigApplyConfiguration) *LoadBalancerApplyConfiguration {
	b.RingHash = value
	return b
}

// WithMaglev sets the Maglev field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Maglev field is set to the value of the last call.
func (b *LoadBalancerApplyConfiguration) WithMaglev(value *LoadBalancerMaglevConfigApplyConfiguration) *LoadBalancerApplyConfiguration {
	b.Maglev = value
	return b
}

// WithRandom sets the Random field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Random field is set to the value of the last call.
func (b *LoadBalancerApplyConfiguration) WithRandom(value apiv1alpha1.LoadBalancerRandomConfig) *LoadBalancerApplyConfiguration {
	b.Random = &value
	return b
}

// WithLocalityType sets the LocalityType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LocalityType field is set to the value of the last call.
func (b *LoadBalancerApplyConfiguration) WithLocalityType(value apiv1alpha1.LocalityType) *LoadBalancerApplyConfiguration {
	b.LocalityType = &value
	return b
}

// WithCloseConnectionsOnHostSetChange sets the CloseConnectionsOnHostSetChange field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CloseConnectionsOnHostSetChange field is set to the value of the last call.
func (b *LoadBalancerApplyConfiguration) WithCloseConnectionsOnHostSetChange(value bool) *LoadBalancerApplyConfiguration {
	b.CloseConnectionsOnHostSetChange = &value
	return b
}
