// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// MCPApplyConfiguration represents a declarative configuration of the MCP type for use
// with apply.
//
// MCP configures mcp backends
type MCPApplyConfiguration struct {
	// Targets is a list of MCP targets to use for this backend.
	// Policies targeting MCP targets must use targetRefs[].sectionName
	// to select the target by name.
	Targets []McpTargetSelectorApplyConfiguration `json:"targets,omitempty"`
}

// MCPApplyConfiguration constructs a declarative configuration of the MCP type for use with
// apply.
func MCP() *MCPApplyConfiguration {
	return &MCPApplyConfiguration{}
}

// WithTargets adds the given value to the Targets field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Targets field.
func (b *MCPApplyConfiguration) WithTargets(values ...*McpTargetSelectorApplyConfiguration) *MCPApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithTargets")
		}
		b.Targets = append(b.Targets, *values[i])
	}
	return b
}
