// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "sigs.k8s.io/gateway-api/apis/v1"
)

// NamespacedObjectReferenceApplyConfiguration represents a declarative configuration of the NamespacedObjectReference type for use
// with apply.
//
// Control-plane RBAC rules not specific to policies:
// Select the object by Name and Namespace.
// You can target only one object at a time.
type NamespacedObjectReferenceApplyConfiguration struct {
	// The name of the target resource.
	Name *v1.ObjectName `json:"name,omitempty"`
	// The namespace of the target resource.
	// If not set, defaults to the namespace of the parent object.
	Namespace *v1.Namespace `json:"namespace,omitempty"`
}

// NamespacedObjectReferenceApplyConfiguration constructs a declarative configuration of the NamespacedObjectReference type for use with
// apply.
func NamespacedObjectReference() *NamespacedObjectReferenceApplyConfiguration {
	return &NamespacedObjectReferenceApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *NamespacedObjectReferenceApplyConfiguration) WithName(value v1.ObjectName) *NamespacedObjectReferenceApplyConfiguration {
	b.Name = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *NamespacedObjectReferenceApplyConfiguration) WithNamespace(value v1.Namespace) *NamespacedObjectReferenceApplyConfiguration {
	b.Namespace = &value
	return b
}
