// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// OpenTelemetryAccessLogServiceApplyConfiguration represents a declarative configuration of the OpenTelemetryAccessLogService type for use
// with apply.
//
// OpenTelemetryAccessLogService represents the OTel configuration for access logs.
// Ref: https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/access_loggers/open_telemetry/v3/logs_service.proto
type OpenTelemetryAccessLogServiceApplyConfiguration struct {
	// Send access logs to gRPC service
	GrpcService *CommonAccessLogGrpcServiceApplyConfiguration `json:"grpcService,omitempty"`
	// OpenTelemetry LogResource fields, following Envoy access logging formatting.
	Body *string `json:"body,omitempty"`
	// If specified, Envoy will not generate built-in resource labels like log_name, zone_name, cluster_name, node_name.
	DisableBuiltinLabels *bool `json:"disableBuiltinLabels,omitempty"`
	// Additional attributes that describe the specific event occurrence.
	Attributes *KeyAnyValueListApplyConfiguration `json:"attributes,omitempty"`
	// Additional resource attributes that describe the resource.
	// If the `service.name` resource attribute is not specified, it adds it with the default value
	// of the envoy cluster name, ie: `<gateway-name>.<gateway-namespace>`
	ResourceAttributes *KeyAnyValueListApplyConfiguration `json:"resourceAttributes,omitempty"`
}

// OpenTelemetryAccessLogServiceApplyConfiguration constructs a declarative configuration of the OpenTelemetryAccessLogService type for use with
// apply.
func OpenTelemetryAccessLogService() *OpenTelemetryAccessLogServiceApplyConfiguration {
	return &OpenTelemetryAccessLogServiceApplyConfiguration{}
}

// WithGrpcService sets the GrpcService field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GrpcService field is set to the value of the last call.
func (b *OpenTelemetryAccessLogServiceApplyConfiguration) WithGrpcService(value *CommonAccessLogGrpcServiceApplyConfiguration) *OpenTelemetryAccessLogServiceApplyConfiguration {
	b.GrpcService = value
	return b
}

// WithBody sets the Body field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Body field is set to the value of the last call.
func (b *OpenTelemetryAccessLogServiceApplyConfiguration) WithBody(value string) *OpenTelemetryAccessLogServiceApplyConfiguration {
	b.Body = &value
	return b
}

// WithDisableBuiltinLabels sets the DisableBuiltinLabels field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DisableBuiltinLabels field is set to the value of the last call.
func (b *OpenTelemetryAccessLogServiceApplyConfiguration) WithDisableBuiltinLabels(value bool) *OpenTelemetryAccessLogServiceApplyConfiguration {
	b.DisableBuiltinLabels = &value
	return b
}

// WithAttributes sets the Attributes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Attributes field is set to the value of the last call.
func (b *OpenTelemetryAccessLogServiceApplyConfiguration) WithAttributes(value *KeyAnyValueListApplyConfiguration) *OpenTelemetryAccessLogServiceApplyConfiguration {
	b.Attributes = value
	return b
}

// WithResourceAttributes sets the ResourceAttributes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResourceAttributes field is set to the value of the last call.
func (b *OpenTelemetryAccessLogServiceApplyConfiguration) WithResourceAttributes(value *KeyAnyValueListApplyConfiguration) *OpenTelemetryAccessLogServiceApplyConfiguration {
	b.ResourceAttributes = value
	return b
}
