// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// PodApplyConfiguration represents a declarative configuration of the Pod type for use
// with apply.
//
// Configuration for a Kubernetes Pod template.
type PodApplyConfiguration struct {
	// Additional labels to add to the Pod object metadata.
	ExtraLabels map[string]string `json:"extraLabels,omitempty"`
	// Additional annotations to add to the Pod object metadata.
	ExtraAnnotations map[string]string `json:"extraAnnotations,omitempty"`
	// The pod security context. See
	// https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.26/#podsecuritycontext-v1-core
	// for details.
	SecurityContext *v1.PodSecurityContext `json:"securityContext,omitempty"`
	// An optional list of references to secrets in the same namespace to use for
	// pulling any of the images used by this Pod spec. See
	// https://kubernetes.io/docs/concepts/containers/images/#specifying-imagepullsecrets-on-a-pod
	// for details.
	ImagePullSecrets []v1.LocalObjectReference `json:"imagePullSecrets,omitempty"`
	// A selector which must be true for the pod to fit on a node. See
	// https://kubernetes.io/docs/concepts/configuration/assign-pod-node/ for
	// details.
	NodeSelector map[string]string `json:"nodeSelector,omitempty"`
	// If specified, the pod's scheduling constraints. See
	// https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.26/#affinity-v1-core
	// for details.
	Affinity *v1.Affinity `json:"affinity,omitempty"`
	// do not use slice of pointers: https://github.com/kubernetes/code-generator/issues/166
	// If specified, the pod's tolerations. See
	// https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.26/#toleration-v1-core
	// for details.
	Tolerations []v1.Toleration `json:"tolerations,omitempty"`
	// If specified, the pod's graceful shutdown spec.
	GracefulShutdown *GracefulShutdownSpecApplyConfiguration `json:"gracefulShutdown,omitempty"`
	// If specified, the pod's termination grace period in seconds. See
	// https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.26/#pod-v1-core
	// for details
	TerminationGracePeriodSeconds *int64 `json:"terminationGracePeriodSeconds,omitempty"`
	// If specified, the pod's startup probe. A probe of container startup readiness.
	// Container will be only be added to service endpoints if the probe succeeds. See
	// https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.26/#probe-v1-core
	// for details.
	StartupProbe *v1.Probe `json:"startupProbe,omitempty"`
	// If specified, the pod's readiness probe. Periodic probe of container service readiness.
	// Container will be removed from service endpoints if the probe fails. See
	// https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.26/#probe-v1-core
	// for details.
	ReadinessProbe *v1.Probe `json:"readinessProbe,omitempty"`
	// If specified, the pod's liveness probe. Periodic probe of container service readiness.
	// Container will be restarted if the probe fails. See
	// https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.26/#probe-v1-core
	// for details.
	LivenessProbe *v1.Probe `json:"livenessProbe,omitempty"`
	// If specified, the pod's topology spread constraints. See
	// https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.26/#topologyspreadconstraint-v1-core
	// for details.
	TopologySpreadConstraints []v1.TopologySpreadConstraint `json:"topologySpreadConstraints,omitempty"`
	// Additional volumes to add to the pod. See
	// https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.26/#volume-v1-core
	// for details.
	ExtraVolumes []v1.Volume `json:"extraVolumes,omitempty"`
}

// PodApplyConfiguration constructs a declarative configuration of the Pod type for use with
// apply.
func Pod() *PodApplyConfiguration {
	return &PodApplyConfiguration{}
}

// WithExtraLabels puts the entries into the ExtraLabels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the ExtraLabels field,
// overwriting an existing map entries in ExtraLabels field with the same key.
func (b *PodApplyConfiguration) WithExtraLabels(entries map[string]string) *PodApplyConfiguration {
	if b.ExtraLabels == nil && len(entries) > 0 {
		b.ExtraLabels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ExtraLabels[k] = v
	}
	return b
}

// WithExtraAnnotations puts the entries into the ExtraAnnotations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the ExtraAnnotations field,
// overwriting an existing map entries in ExtraAnnotations field with the same key.
func (b *PodApplyConfiguration) WithExtraAnnotations(entries map[string]string) *PodApplyConfiguration {
	if b.ExtraAnnotations == nil && len(entries) > 0 {
		b.ExtraAnnotations = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ExtraAnnotations[k] = v
	}
	return b
}

// WithSecurityContext sets the SecurityContext field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecurityContext field is set to the value of the last call.
func (b *PodApplyConfiguration) WithSecurityContext(value v1.PodSecurityContext) *PodApplyConfiguration {
	b.SecurityContext = &value
	return b
}

// WithImagePullSecrets adds the given value to the ImagePullSecrets field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ImagePullSecrets field.
func (b *PodApplyConfiguration) WithImagePullSecrets(values ...v1.LocalObjectReference) *PodApplyConfiguration {
	for i := range values {
		b.ImagePullSecrets = append(b.ImagePullSecrets, values[i])
	}
	return b
}

// WithNodeSelector puts the entries into the NodeSelector field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the NodeSelector field,
// overwriting an existing map entries in NodeSelector field with the same key.
func (b *PodApplyConfiguration) WithNodeSelector(entries map[string]string) *PodApplyConfiguration {
	if b.NodeSelector == nil && len(entries) > 0 {
		b.NodeSelector = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.NodeSelector[k] = v
	}
	return b
}

// WithAffinity sets the Affinity field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Affinity field is set to the value of the last call.
func (b *PodApplyConfiguration) WithAffinity(value v1.Affinity) *PodApplyConfiguration {
	b.Affinity = &value
	return b
}

// WithTolerations adds the given value to the Tolerations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Tolerations field.
func (b *PodApplyConfiguration) WithTolerations(values ...v1.Toleration) *PodApplyConfiguration {
	for i := range values {
		b.Tolerations = append(b.Tolerations, values[i])
	}
	return b
}

// WithGracefulShutdown sets the GracefulShutdown field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GracefulShutdown field is set to the value of the last call.
func (b *PodApplyConfiguration) WithGracefulShutdown(value *GracefulShutdownSpecApplyConfiguration) *PodApplyConfiguration {
	b.GracefulShutdown = value
	return b
}

// WithTerminationGracePeriodSeconds sets the TerminationGracePeriodSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TerminationGracePeriodSeconds field is set to the value of the last call.
func (b *PodApplyConfiguration) WithTerminationGracePeriodSeconds(value int64) *PodApplyConfiguration {
	b.TerminationGracePeriodSeconds = &value
	return b
}

// WithStartupProbe sets the StartupProbe field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StartupProbe field is set to the value of the last call.
func (b *PodApplyConfiguration) WithStartupProbe(value v1.Probe) *PodApplyConfiguration {
	b.StartupProbe = &value
	return b
}

// WithReadinessProbe sets the ReadinessProbe field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReadinessProbe field is set to the value of the last call.
func (b *PodApplyConfiguration) WithReadinessProbe(value v1.Probe) *PodApplyConfiguration {
	b.ReadinessProbe = &value
	return b
}

// WithLivenessProbe sets the LivenessProbe field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LivenessProbe field is set to the value of the last call.
func (b *PodApplyConfiguration) WithLivenessProbe(value v1.Probe) *PodApplyConfiguration {
	b.LivenessProbe = &value
	return b
}

// WithTopologySpreadConstraints adds the given value to the TopologySpreadConstraints field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the TopologySpreadConstraints field.
func (b *PodApplyConfiguration) WithTopologySpreadConstraints(values ...v1.TopologySpreadConstraint) *PodApplyConfiguration {
	for i := range values {
		b.TopologySpreadConstraints = append(b.TopologySpreadConstraints, values[i])
	}
	return b
}

// WithExtraVolumes adds the given value to the ExtraVolumes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ExtraVolumes field.
func (b *PodApplyConfiguration) WithExtraVolumes(values ...v1.Volume) *PodApplyConfiguration {
	for i := range values {
		b.ExtraVolumes = append(b.ExtraVolumes, values[i])
	}
	return b
}
