// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// PriorityGroupApplyConfiguration represents a declarative configuration of the PriorityGroup type for use
// with apply.
//
// MultiPoolConfig configures the backends for multiple hosts or models from the same provider in one Backend resource.
// This method can be useful for creating one logical endpoint that is backed
// by multiple hosts or models.
//
// In the `priorities` section, the order of `pool` entries defines the priority of the backend endpoints.
// The `pool` entries can either define a list of backends or a single backend.
// Note: Only two levels of nesting are permitted. Any nested entries after the second level are ignored.
type PriorityGroupApplyConfiguration struct {
	// A list of LLM provider backends within a single endpoint pool entry.
	Providers []NamedLLMProviderApplyConfiguration `json:"providers,omitempty"`
}

// PriorityGroupApplyConfiguration constructs a declarative configuration of the PriorityGroup type for use with
// apply.
func PriorityGroup() *PriorityGroupApplyConfiguration {
	return &PriorityGroupApplyConfiguration{}
}

// WithProviders adds the given value to the Providers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Providers field.
func (b *PriorityGroupApplyConfiguration) WithProviders(values ...*NamedLLMProviderApplyConfiguration) *PriorityGroupApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithProviders")
		}
		b.Providers = append(b.Providers, *values[i])
	}
	return b
}
