// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// PromptguardRequestApplyConfiguration represents a declarative configuration of the PromptguardRequest type for use
// with apply.
//
// PromptguardRequest defines the prompt guards to apply to requests sent by the client.
// Multiple prompt guard configurations can be set, and they will be executed in the following order:
// webhook → regex → moderation for requests, where each step can reject the request and stop further processing.
type PromptguardRequestApplyConfiguration struct {
	// A custom response message to return to the client. If not specified, defaults to
	// "The request was rejected due to inappropriate content".
	CustomResponse *CustomResponseApplyConfiguration `json:"customResponse,omitempty"`
	// Regular expression (regex) matching for prompt guards and data masking.
	Regex *RegexApplyConfiguration `json:"regex,omitempty"`
	// Configure a webhook to forward requests to for prompt guarding.
	Webhook *WebhookApplyConfiguration `json:"webhook,omitempty"`
	// Pass prompt data through an external moderation model endpoint,
	// which compares the request prompt input to predefined content rules.
	Moderation *ModerationApplyConfiguration `json:"moderation,omitempty"`
}

// PromptguardRequestApplyConfiguration constructs a declarative configuration of the PromptguardRequest type for use with
// apply.
func PromptguardRequest() *PromptguardRequestApplyConfiguration {
	return &PromptguardRequestApplyConfiguration{}
}

// WithCustomResponse sets the CustomResponse field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CustomResponse field is set to the value of the last call.
func (b *PromptguardRequestApplyConfiguration) WithCustomResponse(value *CustomResponseApplyConfiguration) *PromptguardRequestApplyConfiguration {
	b.CustomResponse = value
	return b
}

// WithRegex sets the Regex field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Regex field is set to the value of the last call.
func (b *PromptguardRequestApplyConfiguration) WithRegex(value *RegexApplyConfiguration) *PromptguardRequestApplyConfiguration {
	b.Regex = value
	return b
}

// WithWebhook sets the Webhook field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Webhook field is set to the value of the last call.
func (b *PromptguardRequestApplyConfiguration) WithWebhook(value *WebhookApplyConfiguration) *PromptguardRequestApplyConfiguration {
	b.Webhook = value
	return b
}

// WithModeration sets the Moderation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Moderation field is set to the value of the last call.
func (b *PromptguardRequestApplyConfiguration) WithModeration(value *ModerationApplyConfiguration) *PromptguardRequestApplyConfiguration {
	b.Moderation = value
	return b
}
