// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// PromptguardResponseApplyConfiguration represents a declarative configuration of the PromptguardResponse type for use
// with apply.
//
// PromptguardResponse configures the response that the prompt guard applies to responses returned by the LLM provider.
// Both webhook and regex can be set, they will be executed in the following order: webhook → regex, where each step
// can reject the request and stop further processing.
// Note: This is not yet supported for agentgateway.
type PromptguardResponseApplyConfiguration struct {
	// Regular expression (regex) matching for prompt guards and data masking.
	Regex *RegexApplyConfiguration `json:"regex,omitempty"`
	// Configure a webhook to forward responses to for prompt guarding.
	Webhook *WebhookApplyConfiguration `json:"webhook,omitempty"`
}

// PromptguardResponseApplyConfiguration constructs a declarative configuration of the PromptguardResponse type for use with
// apply.
func PromptguardResponse() *PromptguardResponseApplyConfiguration {
	return &PromptguardResponseApplyConfiguration{}
}

// WithRegex sets the Regex field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Regex field is set to the value of the last call.
func (b *PromptguardResponseApplyConfiguration) WithRegex(value *RegexApplyConfiguration) *PromptguardResponseApplyConfiguration {
	b.Regex = value
	return b
}

// WithWebhook sets the Webhook field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Webhook field is set to the value of the last call.
func (b *PromptguardResponseApplyConfiguration) WithWebhook(value *WebhookApplyConfiguration) *PromptguardResponseApplyConfiguration {
	b.Webhook = value
	return b
}
