// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/apps/v1"
)

// ProxyDeploymentApplyConfiguration represents a declarative configuration of the ProxyDeployment type for use
// with apply.
//
// ProxyDeployment configures the Proxy deployment in Kubernetes.
type ProxyDeploymentApplyConfiguration struct {
	// The number of desired pods.
	// If omitted, behavior will be managed by the K8s control plane, and will default to 1.
	// If you are using an HPA, make sure to not explicitly define this.
	// K8s reference: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#replicas
	Replicas *int32 `json:"replicas,omitempty"`
	// The deployment strategy to use to replace existing pods with new
	// ones. The Kubernetes default is a RollingUpdate with 25% maxUnavailable,
	// 25% maxSurge.
	//
	// E.g., to recreate pods, minimizing resources for the rollout but causing downtime:
	// strategy:
	// type: Recreate
	// E.g., to roll out as a RollingUpdate but with non-default parameters:
	// strategy:
	// type: RollingUpdate
	// rollingUpdate:
	// maxSurge: 100%
	Strategy *v1.DeploymentStrategy `json:"strategy,omitempty"`
}

// ProxyDeploymentApplyConfiguration constructs a declarative configuration of the ProxyDeployment type for use with
// apply.
func ProxyDeployment() *ProxyDeploymentApplyConfiguration {
	return &ProxyDeploymentApplyConfiguration{}
}

// WithReplicas sets the Replicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Replicas field is set to the value of the last call.
func (b *ProxyDeploymentApplyConfiguration) WithReplicas(value int32) *ProxyDeploymentApplyConfiguration {
	b.Replicas = &value
	return b
}

// WithStrategy sets the Strategy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Strategy field is set to the value of the last call.
func (b *ProxyDeploymentApplyConfiguration) WithStrategy(value v1.DeploymentStrategy) *ProxyDeploymentApplyConfiguration {
	b.Strategy = &value
	return b
}
