// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	apiv1alpha1 "github.com/kgateway-dev/kgateway/v2/api/v1alpha1"
)

// RateLimitProviderApplyConfiguration represents a declarative configuration of the RateLimitProvider type for use
// with apply.
//
// RateLimitProvider defines the configuration for a RateLimit service provider.
type RateLimitProviderApplyConfiguration struct {
	// GrpcService is the GRPC service that will handle the rate limiting.
	GrpcService *ExtGrpcServiceApplyConfiguration `json:"grpcService,omitempty"`
	// Domain identifies a rate limiting configuration for the rate limit service.
	// All rate limit requests must specify a domain, which enables the configuration
	// to be per application without fear of overlap (e.g., "api", "web", "admin").
	Domain *string `json:"domain,omitempty"`
	// FailOpen determines if requests are limited when the rate limit service is unavailable.
	// Defaults to true, meaning requests are allowed upstream and not limited if the rate limit service is unavailable.
	FailOpen *bool `json:"failOpen,omitempty"`
	// Timeout provides an optional timeout value for requests to the rate limit service.
	// For rate limiting, prefer using this timeout rather than setting the generic `timeout` on the `GrpcService`.
	// See [envoy issue](https://github.com/envoyproxy/envoy/issues/20070) for more info.
	Timeout *v1.Duration `json:"timeout,omitempty"`
	// XRateLimitHeaders configures the standard version to use for X-RateLimit headers emitted.
	// See [envoy docs](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/ratelimit/v3/rate_limit.proto#envoy-v3-api-field-extensions-filters-http-ratelimit-v3-ratelimit-enable-x-ratelimit-headers) for more info.
	// Disabled by default.
	XRateLimitHeaders *apiv1alpha1.XRateLimitHeadersStandard `json:"xRateLimitHeaders,omitempty"`
}

// RateLimitProviderApplyConfiguration constructs a declarative configuration of the RateLimitProvider type for use with
// apply.
func RateLimitProvider() *RateLimitProviderApplyConfiguration {
	return &RateLimitProviderApplyConfiguration{}
}

// WithGrpcService sets the GrpcService field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GrpcService field is set to the value of the last call.
func (b *RateLimitProviderApplyConfiguration) WithGrpcService(value *ExtGrpcServiceApplyConfiguration) *RateLimitProviderApplyConfiguration {
	b.GrpcService = value
	return b
}

// WithDomain sets the Domain field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Domain field is set to the value of the last call.
func (b *RateLimitProviderApplyConfiguration) WithDomain(value string) *RateLimitProviderApplyConfiguration {
	b.Domain = &value
	return b
}

// WithFailOpen sets the FailOpen field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FailOpen field is set to the value of the last call.
func (b *RateLimitProviderApplyConfiguration) WithFailOpen(value bool) *RateLimitProviderApplyConfiguration {
	b.FailOpen = &value
	return b
}

// WithTimeout sets the Timeout field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Timeout field is set to the value of the last call.
func (b *RateLimitProviderApplyConfiguration) WithTimeout(value v1.Duration) *RateLimitProviderApplyConfiguration {
	b.Timeout = &value
	return b
}

// WithXRateLimitHeaders sets the XRateLimitHeaders field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the XRateLimitHeaders field is set to the value of the last call.
func (b *RateLimitProviderApplyConfiguration) WithXRateLimitHeaders(value apiv1alpha1.XRateLimitHeadersStandard) *RateLimitProviderApplyConfiguration {
	b.XRateLimitHeaders = &value
	return b
}
