// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ResponseFlagFilterApplyConfiguration represents a declarative configuration of the ResponseFlagFilter type for use
// with apply.
//
// ResponseFlagFilter filters based on response flags.
// Based on: https://www.envoyproxy.io/docs/envoy/v1.33.0/api-v3/config/accesslog/v3/accesslog.proto#config-accesslog-v3-responseflagfilter
type ResponseFlagFilterApplyConfiguration struct {
	Flags []string `json:"flags,omitempty"`
}

// ResponseFlagFilterApplyConfiguration constructs a declarative configuration of the ResponseFlagFilter type for use with
// apply.
func ResponseFlagFilter() *ResponseFlagFilterApplyConfiguration {
	return &ResponseFlagFilterApplyConfiguration{}
}

// WithFlags adds the given value to the Flags field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Flags field.
func (b *ResponseFlagFilterApplyConfiguration) WithFlags(values ...string) *ResponseFlagFilterApplyConfiguration {
	for i := range values {
		b.Flags = append(b.Flags, values[i])
	}
	return b
}
