// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	apisv1 "sigs.k8s.io/gateway-api/apis/v1"

	apiv1alpha1 "github.com/kgateway-dev/kgateway/v2/api/v1alpha1"
)

// RetryApplyConfiguration represents a declarative configuration of the Retry type for use
// with apply.
//
// Retry defines the retry policy
type RetryApplyConfiguration struct {
	// RetryOn specifies the conditions under which a retry should be attempted.
	RetryOn []apiv1alpha1.RetryOnCondition `json:"retryOn,omitempty"`
	// Attempts specifies the number of retry attempts for a request.
	// Defaults to 1 attempt if not set.
	// A value of 0 effectively disables retries.
	Attempts *int32 `json:"attempts,omitempty"`
	// PerTryTimeout specifies the timeout per retry attempt (incliding the initial attempt).
	// If a global timeout is configured on a route, this timeout must be less than the global
	// route timeout.
	// It is specified as a sequence of decimal numbers, each with optional fraction and a unit suffix, such as "1s" or "500ms".
	PerTryTimeout *v1.Duration `json:"perTryTimeout,omitempty"`
	// StatusCodes specifies the HTTP status codes in the range 400-599 that should be retried in addition
	// to the conditions specified in RetryOn.
	StatusCodes []apisv1.HTTPRouteRetryStatusCode `json:"statusCodes,omitempty"`
	// BackoffBaseInterval specifies the base interval used with a fully jittered exponential back-off between retries.
	// Defaults to 25ms if not set.
	// Given a backoff base interval B and retry number N, the back-off for the retry is in the range [0, (2^N-1)*B].
	// The backoff interval is capped at a max of 10 times the base interval.
	// E.g., given a value of 25ms, the first retry will be delayed randomly by 0-24ms, the 2nd by 0-74ms,
	// the 3rd by 0-174ms, and so on, and capped to a max of 10 times the base interval (250ms).
	BackoffBaseInterval *v1.Duration `json:"backoffBaseInterval,omitempty"`
}

// RetryApplyConfiguration constructs a declarative configuration of the Retry type for use with
// apply.
func Retry() *RetryApplyConfiguration {
	return &RetryApplyConfiguration{}
}

// WithRetryOn adds the given value to the RetryOn field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the RetryOn field.
func (b *RetryApplyConfiguration) WithRetryOn(values ...apiv1alpha1.RetryOnCondition) *RetryApplyConfiguration {
	for i := range values {
		b.RetryOn = append(b.RetryOn, values[i])
	}
	return b
}

// WithAttempts sets the Attempts field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Attempts field is set to the value of the last call.
func (b *RetryApplyConfiguration) WithAttempts(value int32) *RetryApplyConfiguration {
	b.Attempts = &value
	return b
}

// WithPerTryTimeout sets the PerTryTimeout field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PerTryTimeout field is set to the value of the last call.
func (b *RetryApplyConfiguration) WithPerTryTimeout(value v1.Duration) *RetryApplyConfiguration {
	b.PerTryTimeout = &value
	return b
}

// WithStatusCodes adds the given value to the StatusCodes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the StatusCodes field.
func (b *RetryApplyConfiguration) WithStatusCodes(values ...apisv1.HTTPRouteRetryStatusCode) *RetryApplyConfiguration {
	for i := range values {
		b.StatusCodes = append(b.StatusCodes, values[i])
	}
	return b
}

// WithBackoffBaseInterval sets the BackoffBaseInterval field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BackoffBaseInterval field is set to the value of the last call.
func (b *RetryApplyConfiguration) WithBackoffBaseInterval(value v1.Duration) *RetryApplyConfiguration {
	b.BackoffBaseInterval = &value
	return b
}
