// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// SdsContainerApplyConfiguration represents a declarative configuration of the SdsContainer type for use
// with apply.
//
// SdsContainer configures the container running SDS sidecar.
type SdsContainerApplyConfiguration struct {
	// The SDS container image. See
	// https://kubernetes.io/docs/concepts/containers/images
	// for details.
	Image *ImageApplyConfiguration `json:"image,omitempty"`
	// The security context for this container. See
	// https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.26/#securitycontext-v1-core
	// for details.
	SecurityContext *v1.SecurityContext `json:"securityContext,omitempty"`
	// The compute resources required by this container. See
	// https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
	// for details.
	Resources *v1.ResourceRequirements `json:"resources,omitempty"`
	// Initial SDS container configuration.
	Bootstrap *SdsBootstrapApplyConfiguration `json:"bootstrap,omitempty"`
}

// SdsContainerApplyConfiguration constructs a declarative configuration of the SdsContainer type for use with
// apply.
func SdsContainer() *SdsContainerApplyConfiguration {
	return &SdsContainerApplyConfiguration{}
}

// WithImage sets the Image field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Image field is set to the value of the last call.
func (b *SdsContainerApplyConfiguration) WithImage(value *ImageApplyConfiguration) *SdsContainerApplyConfiguration {
	b.Image = value
	return b
}

// WithSecurityContext sets the SecurityContext field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecurityContext field is set to the value of the last call.
func (b *SdsContainerApplyConfiguration) WithSecurityContext(value v1.SecurityContext) *SdsContainerApplyConfiguration {
	b.SecurityContext = &value
	return b
}

// WithResources sets the Resources field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Resources field is set to the value of the last call.
func (b *SdsContainerApplyConfiguration) WithResources(value v1.ResourceRequirements) *SdsContainerApplyConfiguration {
	b.Resources = &value
	return b
}

// WithBootstrap sets the Bootstrap field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Bootstrap field is set to the value of the last call.
func (b *SdsContainerApplyConfiguration) WithBootstrap(value *SdsBootstrapApplyConfiguration) *SdsContainerApplyConfiguration {
	b.Bootstrap = value
	return b
}
