// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"

	apiv1alpha1 "github.com/kgateway-dev/kgateway/v2/api/v1alpha1"
)

// SingleAuthTokenApplyConfiguration represents a declarative configuration of the SingleAuthToken type for use
// with apply.
//
// SingleAuthToken configures the authorization token that the AI gateway uses to access the LLM provider API.
// This token is automatically sent in a request header, depending on the LLM provider.
type SingleAuthTokenApplyConfiguration struct {
	// Kind specifies which type of authorization token is being used.
	// Must be one of: "Inline", "SecretRef", "Passthrough".
	Kind *apiv1alpha1.SingleAuthTokenKind `json:"kind,omitempty"`
	// Provide the token directly in the configuration for the Backend.
	// This option is the least secure. Only use this option for quick tests such as trying out AI Gateway.
	Inline *string `json:"inline,omitempty"`
	// Store the API key in a Kubernetes secret in the same namespace as the Backend.
	// Then, refer to the secret in the Backend configuration. This option is more secure than an inline token,
	// because the API key is encoded and you can restrict access to secrets through RBAC rules.
	// You might use this option in proofs of concept, controlled development and staging environments,
	// or well-controlled prod environments that use secrets.
	SecretRef *v1.LocalObjectReference `json:"secretRef,omitempty"`
}

// SingleAuthTokenApplyConfiguration constructs a declarative configuration of the SingleAuthToken type for use with
// apply.
func SingleAuthToken() *SingleAuthTokenApplyConfiguration {
	return &SingleAuthTokenApplyConfiguration{}
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *SingleAuthTokenApplyConfiguration) WithKind(value apiv1alpha1.SingleAuthTokenKind) *SingleAuthTokenApplyConfiguration {
	b.Kind = &value
	return b
}

// WithInline sets the Inline field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Inline field is set to the value of the last call.
func (b *SingleAuthTokenApplyConfiguration) WithInline(value string) *SingleAuthTokenApplyConfiguration {
	b.Inline = &value
	return b
}

// WithSecretRef sets the SecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecretRef field is set to the value of the last call.
func (b *SingleAuthTokenApplyConfiguration) WithSecretRef(value v1.LocalObjectReference) *SingleAuthTokenApplyConfiguration {
	b.SecretRef = &value
	return b
}
