// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// SlowStartApplyConfiguration represents a declarative configuration of the SlowStart type for use
// with apply.
type SlowStartApplyConfiguration struct {
	// Represents the size of slow start window.
	// If set, the newly created host remains in slow start mode starting from its creation time
	// for the duration of slow start window.
	Window *v1.Duration `json:"window,omitempty"`
	// This parameter controls the speed of traffic increase over the slow start window. Defaults to 1.0,
	// so that endpoint would get linearly increasing amount of traffic.
	// When increasing the value for this parameter, the speed of traffic ramp-up increases non-linearly.
	// The value of aggression parameter should be greater than 0.0.
	// By tuning the parameter, is possible to achieve polynomial or exponential shape of ramp-up curve.
	//
	// During slow start window, effective weight of an endpoint would be scaled with time factor and aggression:
	// `new_weight = weight * max(min_weight_percent, time_factor ^ (1 / aggression))`,
	// where `time_factor=(time_since_start_seconds / slow_start_time_seconds)`.
	//
	// As time progresses, more and more traffic would be sent to endpoint, which is in slow start window.
	// Once host exits slow start, time_factor and aggression no longer affect its weight.
	Aggression *string `json:"aggression,omitempty"`
	// Minimum weight percentage of an endpoint during slow start.
	MinWeightPercent *int32 `json:"minWeightPercent,omitempty"`
}

// SlowStartApplyConfiguration constructs a declarative configuration of the SlowStart type for use with
// apply.
func SlowStart() *SlowStartApplyConfiguration {
	return &SlowStartApplyConfiguration{}
}

// WithWindow sets the Window field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Window field is set to the value of the last call.
func (b *SlowStartApplyConfiguration) WithWindow(value v1.Duration) *SlowStartApplyConfiguration {
	b.Window = &value
	return b
}

// WithAggression sets the Aggression field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Aggression field is set to the value of the last call.
func (b *SlowStartApplyConfiguration) WithAggression(value string) *SlowStartApplyConfiguration {
	b.Aggression = &value
	return b
}

// WithMinWeightPercent sets the MinWeightPercent field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MinWeightPercent field is set to the value of the last call.
func (b *SlowStartApplyConfiguration) WithMinWeightPercent(value int32) *SlowStartApplyConfiguration {
	b.MinWeightPercent = &value
	return b
}
