// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// StringMatcherApplyConfiguration represents a declarative configuration of the StringMatcher type for use
// with apply.
//
// Specifies the way to match a string.
type StringMatcherApplyConfiguration struct {
	// The input string must match exactly the string specified here.
	// Example: abc matches the value abc
	Exact *string `json:"exact,omitempty"`
	// The input string must have the prefix specified here.
	// Note: empty prefix is not allowed, please use regex instead.
	// Example: abc matches the value abc.xyz
	Prefix *string `json:"prefix,omitempty"`
	// The input string must have the suffix specified here.
	// Note: empty prefix is not allowed, please use regex instead.
	// Example: abc matches the value xyz.abc
	Suffix *string `json:"suffix,omitempty"`
	// The input string must contain the substring specified here.
	// Example: abc matches the value xyz.abc.def
	Contains *string `json:"contains,omitempty"`
	// The input string must match the Google RE2 regular expression specified here.
	// See https://github.com/google/re2/wiki/Syntax for the syntax.
	SafeRegex *string `json:"safeRegex,omitempty"`
	// If true, indicates the exact/prefix/suffix/contains matching should be
	// case insensitive. This has no effect on the regex match.
	// For example, the matcher data will match both input string Data and data if this
	// option is set to true.
	IgnoreCase *bool `json:"ignoreCase,omitempty"`
}

// StringMatcherApplyConfiguration constructs a declarative configuration of the StringMatcher type for use with
// apply.
func StringMatcher() *StringMatcherApplyConfiguration {
	return &StringMatcherApplyConfiguration{}
}

// WithExact sets the Exact field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Exact field is set to the value of the last call.
func (b *StringMatcherApplyConfiguration) WithExact(value string) *StringMatcherApplyConfiguration {
	b.Exact = &value
	return b
}

// WithPrefix sets the Prefix field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Prefix field is set to the value of the last call.
func (b *StringMatcherApplyConfiguration) WithPrefix(value string) *StringMatcherApplyConfiguration {
	b.Prefix = &value
	return b
}

// WithSuffix sets the Suffix field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Suffix field is set to the value of the last call.
func (b *StringMatcherApplyConfiguration) WithSuffix(value string) *StringMatcherApplyConfiguration {
	b.Suffix = &value
	return b
}

// WithContains sets the Contains field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Contains field is set to the value of the last call.
func (b *StringMatcherApplyConfiguration) WithContains(value string) *StringMatcherApplyConfiguration {
	b.Contains = &value
	return b
}

// WithSafeRegex sets the SafeRegex field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SafeRegex field is set to the value of the last call.
func (b *StringMatcherApplyConfiguration) WithSafeRegex(value string) *StringMatcherApplyConfiguration {
	b.SafeRegex = &value
	return b
}

// WithIgnoreCase sets the IgnoreCase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IgnoreCase field is set to the value of the last call.
func (b *StringMatcherApplyConfiguration) WithIgnoreCase(value bool) *StringMatcherApplyConfiguration {
	b.IgnoreCase = &value
	return b
}
