// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// TCPKeepaliveApplyConfiguration represents a declarative configuration of the TCPKeepalive type for use
// with apply.
//
// See [Envoy documentation](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/address.proto#envoy-v3-api-msg-config-core-v3-tcpkeepalive) for more details.
type TCPKeepaliveApplyConfiguration struct {
	// Maximum number of keep-alive probes to send before dropping the connection.
	KeepAliveProbes *int32 `json:"keepAliveProbes,omitempty"`
	// The number of seconds a connection needs to be idle before keep-alive probes start being sent.
	KeepAliveTime *v1.Duration `json:"keepAliveTime,omitempty"`
	// The number of seconds between keep-alive probes.
	KeepAliveInterval *v1.Duration `json:"keepAliveInterval,omitempty"`
}

// TCPKeepaliveApplyConfiguration constructs a declarative configuration of the TCPKeepalive type for use with
// apply.
func TCPKeepalive() *TCPKeepaliveApplyConfiguration {
	return &TCPKeepaliveApplyConfiguration{}
}

// WithKeepAliveProbes sets the KeepAliveProbes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the KeepAliveProbes field is set to the value of the last call.
func (b *TCPKeepaliveApplyConfiguration) WithKeepAliveProbes(value int32) *TCPKeepaliveApplyConfiguration {
	b.KeepAliveProbes = &value
	return b
}

// WithKeepAliveTime sets the KeepAliveTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the KeepAliveTime field is set to the value of the last call.
func (b *TCPKeepaliveApplyConfiguration) WithKeepAliveTime(value v1.Duration) *TCPKeepaliveApplyConfiguration {
	b.KeepAliveTime = &value
	return b
}

// WithKeepAliveInterval sets the KeepAliveInterval field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the KeepAliveInterval field is set to the value of the last call.
func (b *TCPKeepaliveApplyConfiguration) WithKeepAliveInterval(value v1.Duration) *TCPKeepaliveApplyConfiguration {
	b.KeepAliveInterval = &value
	return b
}
