// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// TimeoutsApplyConfiguration represents a declarative configuration of the Timeouts type for use
// with apply.
type TimeoutsApplyConfiguration struct {
	// Request specifies a timeout for an individual request from the gateway to a backend.
	// This spans between the point at which the entire downstream request (i.e. end-of-stream) has been
	// processed and when the backend response has been completely processed.
	// A value of 0 effectively disables the timeout.
	// It is specified as a sequence of decimal numbers, each with optional fraction and a unit suffix, such as "1s" or "500ms".
	Request *v1.Duration `json:"request,omitempty"`
	// StreamIdle specifies a timeout for a requests' idle streams.
	// A value of 0 effectively disables the timeout.
	StreamIdle *v1.Duration `json:"streamIdle,omitempty"`
}

// TimeoutsApplyConfiguration constructs a declarative configuration of the Timeouts type for use with
// apply.
func Timeouts() *TimeoutsApplyConfiguration {
	return &TimeoutsApplyConfiguration{}
}

// WithRequest sets the Request field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Request field is set to the value of the last call.
func (b *TimeoutsApplyConfiguration) WithRequest(value v1.Duration) *TimeoutsApplyConfiguration {
	b.Request = &value
	return b
}

// WithStreamIdle sets the StreamIdle field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StreamIdle field is set to the value of the last call.
func (b *TimeoutsApplyConfiguration) WithStreamIdle(value v1.Duration) *TimeoutsApplyConfiguration {
	b.StreamIdle = &value
	return b
}
