// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// TokenBucketApplyConfiguration represents a declarative configuration of the TokenBucket type for use
// with apply.
//
// TokenBucket defines the configuration for a token bucket rate-limiting mechanism.
// It controls the rate at which tokens are generated and consumed for a specific operation.
type TokenBucketApplyConfiguration struct {
	// MaxTokens specifies the maximum number of tokens that the bucket can hold.
	// This value must be greater than or equal to 1.
	// It determines the burst capacity of the rate limiter.
	MaxTokens *int32 `json:"maxTokens,omitempty"`
	// TokensPerFill specifies the number of tokens added to the bucket during each fill interval.
	// If not specified, it defaults to 1.
	// This controls the steady-state rate of token generation.
	TokensPerFill *int32 `json:"tokensPerFill,omitempty"`
	// FillInterval defines the time duration between consecutive token fills.
	// This value must be a valid duration string (e.g., "1s", "500ms").
	// It determines the frequency of token replenishment.
	FillInterval *v1.Duration `json:"fillInterval,omitempty"`
}

// TokenBucketApplyConfiguration constructs a declarative configuration of the TokenBucket type for use with
// apply.
func TokenBucket() *TokenBucketApplyConfiguration {
	return &TokenBucketApplyConfiguration{}
}

// WithMaxTokens sets the MaxTokens field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxTokens field is set to the value of the last call.
func (b *TokenBucketApplyConfiguration) WithMaxTokens(value int32) *TokenBucketApplyConfiguration {
	b.MaxTokens = &value
	return b
}

// WithTokensPerFill sets the TokensPerFill field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TokensPerFill field is set to the value of the last call.
func (b *TokenBucketApplyConfiguration) WithTokensPerFill(value int32) *TokenBucketApplyConfiguration {
	b.TokensPerFill = &value
	return b
}

// WithFillInterval sets the FillInterval field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FillInterval field is set to the value of the last call.
func (b *TokenBucketApplyConfiguration) WithFillInterval(value v1.Duration) *TokenBucketApplyConfiguration {
	b.FillInterval = &value
	return b
}
