// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// TracingApplyConfiguration represents a declarative configuration of the Tracing type for use
// with apply.
//
// Tracing represents the top-level Envoy's tracer.
// Ref: https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#extensions-filters-network-http-connection-manager-v3-httpconnectionmanager-tracing
type TracingApplyConfiguration struct {
	// Provider defines the upstream to which envoy sends traces
	Provider *TracingProviderApplyConfiguration `json:"provider,omitempty"`
	// Target percentage of requests managed by this HTTP connection manager that will be force traced if the x-client-trace-id header is set. Defaults to 100%
	ClientSampling *int32 `json:"clientSampling,omitempty"`
	// Target percentage of requests managed by this HTTP connection manager that will be randomly selected for trace generation, if not requested by the client or not forced. Defaults to 100%
	RandomSampling *int32 `json:"randomSampling,omitempty"`
	// Target percentage of requests managed by this HTTP connection manager that will be traced after all other sampling checks have been applied (client-directed, force tracing, random sampling). Defaults to 100%
	OverallSampling *int32 `json:"overallSampling,omitempty"`
	// Whether to annotate spans with additional data. If true, spans will include logs for stream events. Defaults to false
	Verbose *bool `json:"verbose,omitempty"`
	// Maximum length of the request path to extract and include in the HttpUrl tag. Used to truncate lengthy request paths to meet the needs of a tracing backend. Default: 256
	MaxPathTagLength *int32 `json:"maxPathTagLength,omitempty"`
	// A list of attributes with a unique name to create attributes for the active span.
	Attributes []CustomAttributeApplyConfiguration `json:"attributes,omitempty"`
	// Create separate tracing span for each upstream request if true. Defaults to false
	// Link to envoy docs for more info
	SpawnUpstreamSpan *bool `json:"spawnUpstreamSpan,omitempty"`
}

// TracingApplyConfiguration constructs a declarative configuration of the Tracing type for use with
// apply.
func Tracing() *TracingApplyConfiguration {
	return &TracingApplyConfiguration{}
}

// WithProvider sets the Provider field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Provider field is set to the value of the last call.
func (b *TracingApplyConfiguration) WithProvider(value *TracingProviderApplyConfiguration) *TracingApplyConfiguration {
	b.Provider = value
	return b
}

// WithClientSampling sets the ClientSampling field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClientSampling field is set to the value of the last call.
func (b *TracingApplyConfiguration) WithClientSampling(value int32) *TracingApplyConfiguration {
	b.ClientSampling = &value
	return b
}

// WithRandomSampling sets the RandomSampling field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RandomSampling field is set to the value of the last call.
func (b *TracingApplyConfiguration) WithRandomSampling(value int32) *TracingApplyConfiguration {
	b.RandomSampling = &value
	return b
}

// WithOverallSampling sets the OverallSampling field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OverallSampling field is set to the value of the last call.
func (b *TracingApplyConfiguration) WithOverallSampling(value int32) *TracingApplyConfiguration {
	b.OverallSampling = &value
	return b
}

// WithVerbose sets the Verbose field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Verbose field is set to the value of the last call.
func (b *TracingApplyConfiguration) WithVerbose(value bool) *TracingApplyConfiguration {
	b.Verbose = &value
	return b
}

// WithMaxPathTagLength sets the MaxPathTagLength field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxPathTagLength field is set to the value of the last call.
func (b *TracingApplyConfiguration) WithMaxPathTagLength(value int32) *TracingApplyConfiguration {
	b.MaxPathTagLength = &value
	return b
}

// WithAttributes adds the given value to the Attributes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Attributes field.
func (b *TracingApplyConfiguration) WithAttributes(values ...*CustomAttributeApplyConfiguration) *TracingApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithAttributes")
		}
		b.Attributes = append(b.Attributes, *values[i])
	}
	return b
}

// WithSpawnUpstreamSpan sets the SpawnUpstreamSpan field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SpawnUpstreamSpan field is set to the value of the last call.
func (b *TracingApplyConfiguration) WithSpawnUpstreamSpan(value bool) *TracingApplyConfiguration {
	b.SpawnUpstreamSpan = &value
	return b
}
