// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// TrafficPolicySpecApplyConfiguration represents a declarative configuration of the TrafficPolicySpec type for use
// with apply.
//
// TrafficPolicySpec defines the desired state of a traffic policy.
// Note: Backend attachment is only supported for agentgateway.
type TrafficPolicySpecApplyConfiguration struct {
	// TargetRefs specifies the target resources by reference to attach the policy to.
	TargetRefs []LocalPolicyTargetReferenceWithSectionNameApplyConfiguration `json:"targetRefs,omitempty"`
	// TargetSelectors specifies the target selectors to select resources to attach the policy to.
	TargetSelectors []LocalPolicyTargetSelectorWithSectionNameApplyConfiguration `json:"targetSelectors,omitempty"`
	// AI is used to configure AI-based policies for the policy.
	AI *AIPolicyApplyConfiguration `json:"ai,omitempty"`
	// Transformation is used to mutate and transform requests and responses
	// before forwarding them to the destination.
	Transformation *TransformationPolicyApplyConfiguration `json:"transformation,omitempty"`
	// ExtProc specifies the external processing configuration for the policy.
	ExtProc *ExtProcPolicyApplyConfiguration `json:"extProc,omitempty"`
	// ExtAuth specifies the external authentication configuration for the policy.
	// This controls what external server to send requests to for authentication.
	ExtAuth *ExtAuthPolicyApplyConfiguration `json:"extAuth,omitempty"`
	// RateLimit specifies the rate limiting configuration for the policy.
	// This controls the rate at which requests are allowed to be processed.
	RateLimit *RateLimitApplyConfiguration `json:"rateLimit,omitempty"`
	// Cors specifies the CORS configuration for the policy.
	Cors *CorsPolicyApplyConfiguration `json:"cors,omitempty"`
	// Csrf specifies the Cross-Site Request Forgery (CSRF) policy for this traffic policy.
	Csrf *CSRFPolicyApplyConfiguration `json:"csrf,omitempty"`
	// HeaderModifiers defines the policy to modify request and response headers.
	HeaderModifiers *HeaderModifiersApplyConfiguration `json:"headerModifiers,omitempty"`
	// AutoHostRewrite rewrites the Host header to the DNS name of the selected upstream.
	// NOTE: This field is only honoured for HTTPRoute targets.
	// NOTE: If `autoHostRewrite` is set on a route that also has a [URLRewrite filter](https://gateway-api.sigs.k8s.io/reference/spec/#httpurlrewritefilter)
	// configured to override the `hostname`, the `hostname` value will be used and `autoHostRewrite` will be ignored.
	AutoHostRewrite *bool `json:"autoHostRewrite,omitempty"`
	// Buffer can be used to set the maximum request size that will be buffered.
	// Requests exceeding this size will return a 413 response.
	Buffer *BufferApplyConfiguration `json:"buffer,omitempty"`
	// Timeouts defines the timeouts for requests
	// It is applicable to HTTPRoutes and ignored for other targeted kinds.
	Timeouts *TimeoutsApplyConfiguration `json:"timeouts,omitempty"`
	// Retry defines the policy for retrying requests.
	// It is applicable to HTTPRoutes, Gateway listeners and XListenerSets, and ignored for other targeted kinds.
	Retry *RetryApplyConfiguration `json:"retry,omitempty"`
	// RBAC specifies the role-based access control configuration for the policy.
	// This defines the rules for authorization based on roles and permissions.
	// With an Envoy-based Gateway, RBAC policies applied at different attachment points in the configuration
	// hierarchy are not cumulative, and only the most specific policy is enforced. In Envoy, this means an RBAC policy
	// attached to a route will override any RBAC policies applied to the gateway or listener. In contrast, an
	// Agentgateway-based Gateway supports cumulative RBAC policies across different attachment points, such that
	// an RBAC policy attached to a route augments policies applied to the gateway or listener without overriding them.
	RBAC *RBACApplyConfiguration `json:"rbac,omitempty"`
}

// TrafficPolicySpecApplyConfiguration constructs a declarative configuration of the TrafficPolicySpec type for use with
// apply.
func TrafficPolicySpec() *TrafficPolicySpecApplyConfiguration {
	return &TrafficPolicySpecApplyConfiguration{}
}

// WithTargetRefs adds the given value to the TargetRefs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the TargetRefs field.
func (b *TrafficPolicySpecApplyConfiguration) WithTargetRefs(values ...*LocalPolicyTargetReferenceWithSectionNameApplyConfiguration) *TrafficPolicySpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithTargetRefs")
		}
		b.TargetRefs = append(b.TargetRefs, *values[i])
	}
	return b
}

// WithTargetSelectors adds the given value to the TargetSelectors field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the TargetSelectors field.
func (b *TrafficPolicySpecApplyConfiguration) WithTargetSelectors(values ...*LocalPolicyTargetSelectorWithSectionNameApplyConfiguration) *TrafficPolicySpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithTargetSelectors")
		}
		b.TargetSelectors = append(b.TargetSelectors, *values[i])
	}
	return b
}

// WithAI sets the AI field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AI field is set to the value of the last call.
func (b *TrafficPolicySpecApplyConfiguration) WithAI(value *AIPolicyApplyConfiguration) *TrafficPolicySpecApplyConfiguration {
	b.AI = value
	return b
}

// WithTransformation sets the Transformation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Transformation field is set to the value of the last call.
func (b *TrafficPolicySpecApplyConfiguration) WithTransformation(value *TransformationPolicyApplyConfiguration) *TrafficPolicySpecApplyConfiguration {
	b.Transformation = value
	return b
}

// WithExtProc sets the ExtProc field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ExtProc field is set to the value of the last call.
func (b *TrafficPolicySpecApplyConfiguration) WithExtProc(value *ExtProcPolicyApplyConfiguration) *TrafficPolicySpecApplyConfiguration {
	b.ExtProc = value
	return b
}

// WithExtAuth sets the ExtAuth field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ExtAuth field is set to the value of the last call.
func (b *TrafficPolicySpecApplyConfiguration) WithExtAuth(value *ExtAuthPolicyApplyConfiguration) *TrafficPolicySpecApplyConfiguration {
	b.ExtAuth = value
	return b
}

// WithRateLimit sets the RateLimit field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RateLimit field is set to the value of the last call.
func (b *TrafficPolicySpecApplyConfiguration) WithRateLimit(value *RateLimitApplyConfiguration) *TrafficPolicySpecApplyConfiguration {
	b.RateLimit = value
	return b
}

// WithCors sets the Cors field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Cors field is set to the value of the last call.
func (b *TrafficPolicySpecApplyConfiguration) WithCors(value *CorsPolicyApplyConfiguration) *TrafficPolicySpecApplyConfiguration {
	b.Cors = value
	return b
}

// WithCsrf sets the Csrf field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Csrf field is set to the value of the last call.
func (b *TrafficPolicySpecApplyConfiguration) WithCsrf(value *CSRFPolicyApplyConfiguration) *TrafficPolicySpecApplyConfiguration {
	b.Csrf = value
	return b
}

// WithHeaderModifiers sets the HeaderModifiers field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HeaderModifiers field is set to the value of the last call.
func (b *TrafficPolicySpecApplyConfiguration) WithHeaderModifiers(value *HeaderModifiersApplyConfiguration) *TrafficPolicySpecApplyConfiguration {
	b.HeaderModifiers = value
	return b
}

// WithAutoHostRewrite sets the AutoHostRewrite field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AutoHostRewrite field is set to the value of the last call.
func (b *TrafficPolicySpecApplyConfiguration) WithAutoHostRewrite(value bool) *TrafficPolicySpecApplyConfiguration {
	b.AutoHostRewrite = &value
	return b
}

// WithBuffer sets the Buffer field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Buffer field is set to the value of the last call.
func (b *TrafficPolicySpecApplyConfiguration) WithBuffer(value *BufferApplyConfiguration) *TrafficPolicySpecApplyConfiguration {
	b.Buffer = value
	return b
}

// WithTimeouts sets the Timeouts field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Timeouts field is set to the value of the last call.
func (b *TrafficPolicySpecApplyConfiguration) WithTimeouts(value *TimeoutsApplyConfiguration) *TrafficPolicySpecApplyConfiguration {
	b.Timeouts = value
	return b
}

// WithRetry sets the Retry field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Retry field is set to the value of the last call.
func (b *TrafficPolicySpecApplyConfiguration) WithRetry(value *RetryApplyConfiguration) *TrafficPolicySpecApplyConfiguration {
	b.Retry = value
	return b
}

// WithRBAC sets the RBAC field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RBAC field is set to the value of the last call.
func (b *TrafficPolicySpecApplyConfiguration) WithRBAC(value *RBACApplyConfiguration) *TrafficPolicySpecApplyConfiguration {
	b.RBAC = value
	return b
}
