// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/kgateway-dev/kgateway/v2/api/v1alpha1"
)

// VertexAIConfigApplyConfiguration represents a declarative configuration of the VertexAIConfig type for use
// with apply.
//
// VertexAIConfig settings for the [Vertex AI](https://cloud.google.com/vertex-ai/docs) LLM provider.
// To find the values for the project ID, project location, and publisher, you can check the fields of an API request, such as
// `https://{LOCATION}-aiplatform.googleapis.com/{VERSION}/projects/{PROJECT_ID}/locations/{LOCATION}/publishers/{PROVIDER}/<model-path>`.
type VertexAIConfigApplyConfiguration struct {
	// The authorization token that the AI gateway uses to access the Vertex AI API.
	// This token is automatically sent in the `key` header of the request.
	AuthToken *SingleAuthTokenApplyConfiguration `json:"authToken,omitempty"`
	// The Vertex AI model to use.
	// For more information, see the [Vertex AI model docs](https://cloud.google.com/vertex-ai/generative-ai/docs/learn/models).
	Model *string `json:"model,omitempty"`
	// The version of the Vertex AI API to use.
	// For more information, see the [Vertex AI API reference](https://cloud.google.com/vertex-ai/docs/reference#versions).
	ApiVersion *string `json:"apiVersion,omitempty"`
	// The ID of the Google Cloud Project that you use for the Vertex AI.
	ProjectId *string `json:"projectId,omitempty"`
	// The location of the Google Cloud Project that you use for the Vertex AI.
	Location *string `json:"location,omitempty"`
	// Optional: The model path to route to. Defaults to the Gemini model path, `generateContent`.
	ModelPath *string `json:"modelPath,omitempty"`
	// The type of publisher model to use. Currently, only Google is supported.
	Publisher *apiv1alpha1.Publisher `json:"publisher,omitempty"`
}

// VertexAIConfigApplyConfiguration constructs a declarative configuration of the VertexAIConfig type for use with
// apply.
func VertexAIConfig() *VertexAIConfigApplyConfiguration {
	return &VertexAIConfigApplyConfiguration{}
}

// WithAuthToken sets the AuthToken field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AuthToken field is set to the value of the last call.
func (b *VertexAIConfigApplyConfiguration) WithAuthToken(value *SingleAuthTokenApplyConfiguration) *VertexAIConfigApplyConfiguration {
	b.AuthToken = value
	return b
}

// WithModel sets the Model field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Model field is set to the value of the last call.
func (b *VertexAIConfigApplyConfiguration) WithModel(value string) *VertexAIConfigApplyConfiguration {
	b.Model = &value
	return b
}

// WithApiVersion sets the ApiVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ApiVersion field is set to the value of the last call.
func (b *VertexAIConfigApplyConfiguration) WithApiVersion(value string) *VertexAIConfigApplyConfiguration {
	b.ApiVersion = &value
	return b
}

// WithProjectId sets the ProjectId field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProjectId field is set to the value of the last call.
func (b *VertexAIConfigApplyConfiguration) WithProjectId(value string) *VertexAIConfigApplyConfiguration {
	b.ProjectId = &value
	return b
}

// WithLocation sets the Location field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Location field is set to the value of the last call.
func (b *VertexAIConfigApplyConfiguration) WithLocation(value string) *VertexAIConfigApplyConfiguration {
	b.Location = &value
	return b
}

// WithModelPath sets the ModelPath field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ModelPath field is set to the value of the last call.
func (b *VertexAIConfigApplyConfiguration) WithModelPath(value string) *VertexAIConfigApplyConfiguration {
	b.ModelPath = &value
	return b
}

// WithPublisher sets the Publisher field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Publisher field is set to the value of the last call.
func (b *VertexAIConfigApplyConfiguration) WithPublisher(value apiv1alpha1.Publisher) *VertexAIConfigApplyConfiguration {
	b.Publisher = &value
	return b
}
