// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "sigs.k8s.io/gateway-api/apis/v1"
)

// WebhookApplyConfiguration represents a declarative configuration of the Webhook type for use
// with apply.
//
// Webhook configures a webhook to forward requests or responses to for prompt guarding.
type WebhookApplyConfiguration struct {
	// Host to send the traffic to.
	// Note: TLS is not currently supported for webhook.
	// Example:
	// ```yaml
	// host:
	// host: example.com  #The host name of the webhook endpoint.
	// port: 443 	        #The port number on which the webhook is listening.
	// ```
	Host *HostApplyConfiguration `json:"host,omitempty"`
	// ForwardHeaderMatches defines a list of HTTP header matches that will be
	// used to select the headers to forward to the webhook.
	// Request headers are used when forwarding requests and response headers
	// are used when forwarding responses.
	// By default, no headers are forwarded.
	ForwardHeaderMatches []v1.HTTPHeaderMatch `json:"forwardHeaderMatches,omitempty"`
}

// WebhookApplyConfiguration constructs a declarative configuration of the Webhook type for use with
// apply.
func Webhook() *WebhookApplyConfiguration {
	return &WebhookApplyConfiguration{}
}

// WithHost sets the Host field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Host field is set to the value of the last call.
func (b *WebhookApplyConfiguration) WithHost(value *HostApplyConfiguration) *WebhookApplyConfiguration {
	b.Host = value
	return b
}

// WithForwardHeaderMatches adds the given value to the ForwardHeaderMatches field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ForwardHeaderMatches field.
func (b *WebhookApplyConfiguration) WithForwardHeaderMatches(values ...v1.HTTPHeaderMatch) *WebhookApplyConfiguration {
	for i := range values {
		b.ForwardHeaderMatches = append(b.ForwardHeaderMatches, values[i])
	}
	return b
}
