{{- $gateway := .Values.gateway }}
{{- if not $gateway.customConfigMapName }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kgateway.gateway.fullname" . }}
  annotations:
    {{- toYaml ($gateway.gatewayAnnotations| default dict) | nindent 4 }}
  labels:
    {{- toYaml $labels | nindent 4 }}
data:
  config.yaml: |
    config: {}
{{- end }}
