{{- $gateway := .Values.gateway }}
{{- if and $gateway.agwXds.tls $gateway.agwXds.tls.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kgateway.gateway.fullname" . }}-xds-ca
  labels:
    {{- include "kgateway.gateway.constLabels" . | nindent 4 }}
    {{- include "kgateway.gateway.labels" . | nindent 4 }}
data:
  ca.crt: |
{{ $gateway.agwXds.tls.caCert | indent 4 }}
{{- end }}
